<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transferinstructions.proto

namespace Io\Token\Proto\Common\Transferinstructions\TransferDestination;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Polish domestic
 *
 * Generated from protobuf message <code>io.token.proto.common.transferinstructions.TransferDestination.ExpressElixir</code>
 */
class ExpressElixir extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string account_number = 1;</code>
     */
    private $account_number = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $account_number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transferinstructions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string account_number = 1;</code>
     * @return string
     */
    public function getAccountNumber()
    {
        return $this->account_number;
    }

    /**
     * Generated from protobuf field <code>string account_number = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_number = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ExpressElixir::class, \Io\Token\Proto\Common\Transferinstructions\TransferDestination_ExpressElixir::class);

