<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blob.proto

namespace GPBMetadata;

class Blob
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Extensions\Field::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa2030a0a626c6f622e70726f746f121a696f2e746f6b656e2e70726f74" .
            "6f2e636f6d6d6f6e2e626c6f622284020a04426c6f62120a0a0269641801" .
            "20012809123f0a077061796c6f616418022001280b32282e696f2e746f6b" .
            "656e2e70726f746f2e636f6d6d6f6e2e626c6f622e426c6f622e5061796c" .
            "6f6164420480b518011a87010a075061796c6f616412100a086f776e6572" .
            "5f6964180120012809120c0a0474797065180220012809120c0a046e616d" .
            "65180320012809120c0a046461746118042001280c12400a0b6163636573" .
            "735f6d6f646518052001280e322b2e696f2e746f6b656e2e70726f746f2e" .
            "636f6d6d6f6e2e626c6f622e426c6f622e4163636573734d6f646522250a" .
            "0a4163636573734d6f6465120b0a0744454641554c541000120a0a065055" .
            "424c4943100122390a0a4174746163686d656e74120f0a07626c6f625f69" .
            "64180120012809120c0a0474797065180220012809120c0a046e616d6518" .
            "0320012809422e420a426c6f6250726f746f73aa021f546f6b656e696f2e" .
            "50726f746f2e436f6d6d6f6e2e426c6f6250726f746f73620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

