<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consent.proto

namespace Io\Token\Proto\Common\Consent\Consent;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.consent.Consent.InformationAccess</code>
 */
class InformationAccess extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .io.token.proto.common.consent.Consent.InformationAccess.ResourceAccess resource_access = 1;</code>
     */
    private $resource_access;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Consent\Consent\InformationAccess\ResourceAccess[]|\Google\Protobuf\Internal\RepeatedField $resource_access
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Consent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .io.token.proto.common.consent.Consent.InformationAccess.ResourceAccess resource_access = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResourceAccess()
    {
        return $this->resource_access;
    }

    /**
     * Generated from protobuf field <code>repeated .io.token.proto.common.consent.Consent.InformationAccess.ResourceAccess resource_access = 1;</code>
     * @param \Io\Token\Proto\Common\Consent\Consent\InformationAccess\ResourceAccess[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResourceAccess($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Token\Proto\Common\Consent\Consent\InformationAccess\ResourceAccess::class);
        $this->resource_access = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(InformationAccess::class, \Io\Token\Proto\Common\Consent\Consent_InformationAccess::class);

