<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

namespace Io\Token\Proto\Common\Member\MemberOperationMetadata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.member.MemberOperationMetadata.AddAliasMetadata</code>
 */
class AddAliasMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string alias_hash = 1;</code>
     */
    private $alias_hash = '';
    /**
     * Generated from protobuf field <code>.io.token.proto.common.alias.Alias alias = 2;</code>
     */
    private $alias = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $alias_hash
     *     @type \Io\Token\Proto\Common\Alias\Alias $alias
     * }
     */
    public function __construct($data = NULL) {
        \Io\Token\GPBMetadata\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string alias_hash = 1;</code>
     * @return string
     */
    public function getAliasHash()
    {
        return $this->alias_hash;
    }

    /**
     * Generated from protobuf field <code>string alias_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAliasHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->alias_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.alias.Alias alias = 2;</code>
     * @return \Io\Token\Proto\Common\Alias\Alias
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.alias.Alias alias = 2;</code>
     * @param \Io\Token\Proto\Common\Alias\Alias $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Alias\Alias::class);
        $this->alias = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AddAliasMetadata::class, \Io\Token\Proto\Common\Member\MemberOperationMetadata_AddAliasMetadata::class);

