version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: paragonie/sodium_compat
    versions:
    - 1.14.0
    - 1.15.3
  - dependency-name: google/protobuf
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: composer/composer
    versions:
    - 2.0.10
    - 2.0.11
    - 2.0.12
    - 2.0.9
  - dependency-name: grpc/grpc
    versions:
    - 1.35.0
