<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Io\Token\Proto\Common\Account\AccountIdentifier;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.account.AccountIdentifier.Bban</code>
 */
class Bban extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string bban = 1;</code>
     */
    private $bban = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bban
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string bban = 1;</code>
     * @return string
     */
    public function getBban()
    {
        return $this->bban;
    }

    /**
     * Generated from protobuf field <code>string bban = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBban($var)
    {
        GPBUtil::checkString($var, True);
        $this->bban = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Bban::class, \Io\Token\Proto\Common\Account\AccountIdentifier_Bban::class);

