<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto

namespace Io\Token\Proto\Common\Token\TokenRequestPayload\AccessBody\AccountResourceList;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.token.TokenRequestPayload.AccessBody.AccountResourceList.AccountResource</code>
 */
class AccountResource extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenRequestPayload.AccessBody.AccountResourceType type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>.io.token.proto.common.account.BankAccount bank_account = 2;</code>
     */
    private $bank_account = null;
    /**
     * Generated from protobuf field <code>.io.token.proto.common.transferinstructions.CustomerData customer_data = 3;</code>
     */
    private $customer_data = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type \Io\Token\Proto\Common\Account\BankAccount $bank_account
     *     @type \Io\Token\Proto\Common\Transferinstructions\CustomerData $customer_data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Token::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenRequestPayload.AccessBody.AccountResourceType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenRequestPayload.AccessBody.AccountResourceType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Io\Token\Proto\Common\Token\TokenRequestPayload_AccessBody_AccountResourceType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.account.BankAccount bank_account = 2;</code>
     * @return \Io\Token\Proto\Common\Account\BankAccount
     */
    public function getBankAccount()
    {
        return $this->bank_account;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.account.BankAccount bank_account = 2;</code>
     * @param \Io\Token\Proto\Common\Account\BankAccount $var
     * @return $this
     */
    public function setBankAccount($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Account\BankAccount::class);
        $this->bank_account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.transferinstructions.CustomerData customer_data = 3;</code>
     * @return \Io\Token\Proto\Common\Transferinstructions\CustomerData
     */
    public function getCustomerData()
    {
        return $this->customer_data;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.transferinstructions.CustomerData customer_data = 3;</code>
     * @param \Io\Token\Proto\Common\Transferinstructions\CustomerData $var
     * @return $this
     */
    public function setCustomerData($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Transferinstructions\CustomerData::class);
        $this->customer_data = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AccountResource::class, \Io\Token\Proto\Common\Token\TokenRequestPayload_AccessBody_AccountResourceList_AccountResource::class);

