<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

namespace Io\Token\Proto\Common\Member;

/**
 * Protobuf type <code>io.token.proto.common.member.CreateMemberType</code>
 */
class CreateMemberType
{
    /**
     * Generated from protobuf enum <code>INVALID_MEMBER_TYPE = 0;</code>
     */
    const INVALID_MEMBER_TYPE = 0;
    /**
     * Generated from protobuf enum <code>PERSONAL = 1;</code>
     */
    const PERSONAL = 1;
    /**
     * Generated from protobuf enum <code>BUSINESS = 2;</code>
     */
    const BUSINESS = 2;
    /**
     * Generated from protobuf enum <code>TRANSIENT = 3;</code>
     */
    const TRANSIENT = 3;
}

