<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

namespace Io\Token\Proto\Common\Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.member.MemberInfo</code>
 */
class MemberInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * verified aliases
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.alias.Alias aliases = 2;</code>
     */
    private $aliases;
    /**
     * Generated from protobuf field <code>string profile_name = 3;</code>
     */
    private $profile_name = '';
    /**
     * Generated from protobuf field <code>int64 created_at_ms = 4;</code>
     */
    private $created_at_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \Io\Token\Proto\Common\Alias\Alias[]|\Google\Protobuf\Internal\RepeatedField $aliases
     *           verified aliases
     *     @type string $profile_name
     *     @type int|string $created_at_ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * verified aliases
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.alias.Alias aliases = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAliases()
    {
        return $this->aliases;
    }

    /**
     * verified aliases
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.alias.Alias aliases = 2;</code>
     * @param \Io\Token\Proto\Common\Alias\Alias[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAliases($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Token\Proto\Common\Alias\Alias::class);
        $this->aliases = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string profile_name = 3;</code>
     * @return string
     */
    public function getProfileName()
    {
        return $this->profile_name;
    }

    /**
     * Generated from protobuf field <code>string profile_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setProfileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->profile_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 created_at_ms = 4;</code>
     * @return int|string
     */
    public function getCreatedAtMs()
    {
        return $this->created_at_ms;
    }

    /**
     * Generated from protobuf field <code>int64 created_at_ms = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAtMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->created_at_ms = $var;

        return $this;
    }

}

