<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

namespace Io\Token\Proto\Common\Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Provides an agent signature authorizing the recovery operation. Multiple authorizations
 * might be required in order to initiate the recovery process.  The number of required signatures
 * is governed by Recovery Rules associated with the member.
 *
 * Generated from protobuf message <code>io.token.proto.common.member.MemberRecoveryOperation</code>
 */
class MemberRecoveryOperation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.io.token.proto.common.member.MemberRecoveryOperation.Authorization authorization = 1;</code>
     */
    private $authorization = null;
    /**
     * Java SDK Member.authorizeRecovery can generate signature
     * https://developer.token.io/sdk/javadoc/io/token/Member.html#authorizeRecovery-io.token.proto.common.member.MemberProtos.MemberRecoveryOperation.Authorization-
     *
     * Generated from protobuf field <code>.io.token.proto.common.security.Signature agent_signature = 2;</code>
     */
    private $agent_signature = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Member\MemberRecoveryOperation\Authorization $authorization
     *     @type \Io\Token\Proto\Common\Security\Signature $agent_signature
     *           Java SDK Member.authorizeRecovery can generate signature
     *           https://developer.token.io/sdk/javadoc/io/token/Member.html#authorizeRecovery-io.token.proto.common.member.MemberProtos.MemberRecoveryOperation.Authorization-
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.member.MemberRecoveryOperation.Authorization authorization = 1;</code>
     * @return \Io\Token\Proto\Common\Member\MemberRecoveryOperation\Authorization
     */
    public function getAuthorization()
    {
        return $this->authorization;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.member.MemberRecoveryOperation.Authorization authorization = 1;</code>
     * @param \Io\Token\Proto\Common\Member\MemberRecoveryOperation\Authorization $var
     * @return $this
     */
    public function setAuthorization($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Member\MemberRecoveryOperation_Authorization::class);
        $this->authorization = $var;

        return $this;
    }

    /**
     * Java SDK Member.authorizeRecovery can generate signature
     * https://developer.token.io/sdk/javadoc/io/token/Member.html#authorizeRecovery-io.token.proto.common.member.MemberProtos.MemberRecoveryOperation.Authorization-
     *
     * Generated from protobuf field <code>.io.token.proto.common.security.Signature agent_signature = 2;</code>
     * @return \Io\Token\Proto\Common\Security\Signature
     */
    public function getAgentSignature()
    {
        return $this->agent_signature;
    }

    /**
     * Java SDK Member.authorizeRecovery can generate signature
     * https://developer.token.io/sdk/javadoc/io/token/Member.html#authorizeRecovery-io.token.proto.common.member.MemberProtos.MemberRecoveryOperation.Authorization-
     *
     * Generated from protobuf field <code>.io.token.proto.common.security.Signature agent_signature = 2;</code>
     * @param \Io\Token\Proto\Common\Security\Signature $var
     * @return $this
     */
    public function setAgentSignature($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Security\Signature::class);
        $this->agent_signature = $var;

        return $this;
    }

}

