<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

namespace Io\Token\Proto\Common\Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Metadata associated with MemberUpdate.
 * It is outside of MemberUpdate because MemberUpdate is signed and passed to the Directory.
 *
 * Generated from protobuf message <code>io.token.proto.common.member.MemberOperationMetadata</code>
 */
class MemberOperationMetadata extends \Google\Protobuf\Internal\Message
{
    protected $type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Member\MemberOperationMetadata\AddAliasMetadata $add_alias_metadata
     * }
     */
    public function __construct($data = NULL) {
        \Io\Token\GPBMetadata\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.member.MemberOperationMetadata.AddAliasMetadata add_alias_metadata = 1;</code>
     * @return \Io\Token\Proto\Common\Member\MemberOperationMetadata\AddAliasMetadata
     */
    public function getAddAliasMetadata()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.member.MemberOperationMetadata.AddAliasMetadata add_alias_metadata = 1;</code>
     * @param \Io\Token\Proto\Common\Member\MemberOperationMetadata\AddAliasMetadata $var
     * @return $this
     */
    public function setAddAliasMetadata($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Member\MemberOperationMetadata_AddAliasMetadata::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->whichOneof("type");
    }

}

