<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

namespace Io\Token\Proto\Common\Member;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Member\MemberRecoveryOperation\Authorization instead.
     * @deprecated
     */
    class MemberRecoveryOperation_Authorization {}
}
class_exists(MemberRecoveryOperation\Authorization::class);
@trigger_error('Io\Token\Proto\Common\Member\MemberRecoveryOperation_Authorization is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Member\MemberRecoveryOperation\Authorization instead', E_USER_DEPRECATED);

