<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

namespace Io\Token\Proto\Common\Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Adds/removes member alias to/from the directory.
 *
 * Generated from protobuf message <code>io.token.proto.common.member.MemberAliasOperation</code>
 */
class MemberAliasOperation extends \Google\Protobuf\Internal\Message
{
    /**
     * Hash of alias to add/remove
     * https://developer.token.io/sdk/esdoc/class/src/Util.js~Util.html#static-method-hashAndSerializeAlias
     *
     * Generated from protobuf field <code>string alias_hash = 1;</code>
     */
    private $alias_hash = '';
    /**
     * Realm of alias to add/remove
     *
     * Generated from protobuf field <code>string realm = 2 [deprecated = true];</code>
     */
    private $realm = '';
    /**
     * Generated from protobuf field <code>string realm_id = 3;</code>
     */
    private $realm_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $alias_hash
     *           Hash of alias to add/remove
     *           https://developer.token.io/sdk/esdoc/class/src/Util.js~Util.html#static-method-hashAndSerializeAlias
     *     @type string $realm
     *           Realm of alias to add/remove
     *     @type string $realm_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * Hash of alias to add/remove
     * https://developer.token.io/sdk/esdoc/class/src/Util.js~Util.html#static-method-hashAndSerializeAlias
     *
     * Generated from protobuf field <code>string alias_hash = 1;</code>
     * @return string
     */
    public function getAliasHash()
    {
        return $this->alias_hash;
    }

    /**
     * Hash of alias to add/remove
     * https://developer.token.io/sdk/esdoc/class/src/Util.js~Util.html#static-method-hashAndSerializeAlias
     *
     * Generated from protobuf field <code>string alias_hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAliasHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->alias_hash = $var;

        return $this;
    }

    /**
     * Realm of alias to add/remove
     *
     * Generated from protobuf field <code>string realm = 2 [deprecated = true];</code>
     * @return string
     */
    public function getRealm()
    {
        return $this->realm;
    }

    /**
     * Realm of alias to add/remove
     *
     * Generated from protobuf field <code>string realm = 2 [deprecated = true];</code>
     * @param string $var
     * @return $this
     */
    public function setRealm($var)
    {
        GPBUtil::checkString($var, True);
        $this->realm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string realm_id = 3;</code>
     * @return string
     */
    public function getRealmId()
    {
        return $this->realm_id;
    }

    /**
     * Generated from protobuf field <code>string realm_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRealmId($var)
    {
        GPBUtil::checkString($var, True);
        $this->realm_id = $var;

        return $this;
    }

}

