<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

namespace Io\Token\Proto\Common\Member;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A recovery rule specifies which signatures are required for a member reset operation.
 *
 * Generated from protobuf message <code>io.token.proto.common.member.RecoveryRule</code>
 */
class RecoveryRule extends \Google\Protobuf\Internal\Message
{
    /**
     * the member id of the primary agent
     *
     * Generated from protobuf field <code>string primary_agent = 1;</code>
     */
    private $primary_agent = '';
    /**
     * an optional list of member ids acting as secondary agents
     *
     * Generated from protobuf field <code>repeated string secondary_agents = 2;</code>
     */
    private $secondary_agents;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $primary_agent
     *           the member id of the primary agent
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $secondary_agents
     *           an optional list of member ids acting as secondary agents
     * }
     */
    public function __construct($data = NULL) {
        \Io\Token\GPBMetadata\Member::initOnce();
        parent::__construct($data);
    }

    /**
     * the member id of the primary agent
     *
     * Generated from protobuf field <code>string primary_agent = 1;</code>
     * @return string
     */
    public function getPrimaryAgent()
    {
        return $this->primary_agent;
    }

    /**
     * the member id of the primary agent
     *
     * Generated from protobuf field <code>string primary_agent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPrimaryAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->primary_agent = $var;

        return $this;
    }

    /**
     * an optional list of member ids acting as secondary agents
     *
     * Generated from protobuf field <code>repeated string secondary_agents = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSecondaryAgents()
    {
        return $this->secondary_agents;
    }

    /**
     * an optional list of member ids acting as secondary agents
     *
     * Generated from protobuf field <code>repeated string secondary_agents = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSecondaryAgents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->secondary_agents = $arr;

        return $this;
    }

}

