<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security.proto

namespace Io\Token\Proto\Common\Security;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Security\Key\Algorithm instead.
     * @deprecated
     */
    class Key_Algorithm {}
}
class_exists(Key\Algorithm::class);
@trigger_error('Io\Token\Proto\Common\Security\Key_Algorithm is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Security\Key\Algorithm instead', E_USER_DEPRECATED);

