<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Io\Token\Proto\Common\Account;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Account\AccountIdentifier\Bban instead.
     * @deprecated
     */
    class AccountIdentifier_Bban {}
}
class_exists(AccountIdentifier\Bban::class);
@trigger_error('Io\Token\Proto\Common\Account\AccountIdentifier_Bban is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Account\AccountIdentifier\Bban instead', E_USER_DEPRECATED);

