<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Io\Token\Proto\Common\Account;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Not all accounts support all Token features.
 *
 * Generated from protobuf message <code>io.token.proto.common.account.AccountFeatures</code>
 */
class AccountFeatures extends \Google\Protobuf\Internal\Message
{
    /**
     * **DEPRECATED** can both send and receive payments
     *
     * Generated from protobuf field <code>bool supports_payment = 1;</code>
     */
    private $supports_payment = false;
    /**
     * can get info, e.g., get balance
     *
     * Generated from protobuf field <code>bool supports_information = 2;</code>
     */
    private $supports_information = false;
    /**
     * Generated from protobuf field <code>bool requires_external_auth = 3;</code>
     */
    private $requires_external_auth = false;
    /**
     * can send payments from account
     *
     * Generated from protobuf field <code>bool supports_send_payment = 4;</code>
     */
    private $supports_send_payment = false;
    /**
     * can receive payments to account
     *
     * Generated from protobuf field <code>bool supports_receive_payment = 5;</code>
     */
    private $supports_receive_payment = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $supports_payment
     *           **DEPRECATED** can both send and receive payments
     *     @type bool $supports_information
     *           can get info, e.g., get balance
     *     @type bool $requires_external_auth
     *     @type bool $supports_send_payment
     *           can send payments from account
     *     @type bool $supports_receive_payment
     *           can receive payments to account
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * **DEPRECATED** can both send and receive payments
     *
     * Generated from protobuf field <code>bool supports_payment = 1;</code>
     * @return bool
     */
    public function getSupportsPayment()
    {
        return $this->supports_payment;
    }

    /**
     * **DEPRECATED** can both send and receive payments
     *
     * Generated from protobuf field <code>bool supports_payment = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupportsPayment($var)
    {
        GPBUtil::checkBool($var);
        $this->supports_payment = $var;

        return $this;
    }

    /**
     * can get info, e.g., get balance
     *
     * Generated from protobuf field <code>bool supports_information = 2;</code>
     * @return bool
     */
    public function getSupportsInformation()
    {
        return $this->supports_information;
    }

    /**
     * can get info, e.g., get balance
     *
     * Generated from protobuf field <code>bool supports_information = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupportsInformation($var)
    {
        GPBUtil::checkBool($var);
        $this->supports_information = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool requires_external_auth = 3;</code>
     * @return bool
     */
    public function getRequiresExternalAuth()
    {
        return $this->requires_external_auth;
    }

    /**
     * Generated from protobuf field <code>bool requires_external_auth = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setRequiresExternalAuth($var)
    {
        GPBUtil::checkBool($var);
        $this->requires_external_auth = $var;

        return $this;
    }

    /**
     * can send payments from account
     *
     * Generated from protobuf field <code>bool supports_send_payment = 4;</code>
     * @return bool
     */
    public function getSupportsSendPayment()
    {
        return $this->supports_send_payment;
    }

    /**
     * can send payments from account
     *
     * Generated from protobuf field <code>bool supports_send_payment = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupportsSendPayment($var)
    {
        GPBUtil::checkBool($var);
        $this->supports_send_payment = $var;

        return $this;
    }

    /**
     * can receive payments to account
     *
     * Generated from protobuf field <code>bool supports_receive_payment = 5;</code>
     * @return bool
     */
    public function getSupportsReceivePayment()
    {
        return $this->supports_receive_payment;
    }

    /**
     * can receive payments to account
     *
     * Generated from protobuf field <code>bool supports_receive_payment = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setSupportsReceivePayment($var)
    {
        GPBUtil::checkBool($var);
        $this->supports_receive_payment = $var;

        return $this;
    }

}

