<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Io\Token\Proto\Common\Account;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Account\BankAccount\Guest instead.
     * @deprecated
     */
    class BankAccount_Guest {}
}
class_exists(BankAccount\Guest::class);
@trigger_error('Io\Token\Proto\Common\Account\BankAccount_Guest is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Account\BankAccount\Guest instead', E_USER_DEPRECATED);

