<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Io\Token\Proto\Common\Account;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Account\BankAccount\TokenAuthorization instead.
     * @deprecated
     */
    class BankAccount_TokenAuthorization {}
}
class_exists(BankAccount\TokenAuthorization::class);
@trigger_error('Io\Token\Proto\Common\Account\BankAccount_TokenAuthorization is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Account\BankAccount\TokenAuthorization instead', E_USER_DEPRECATED);

