<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Io\Token\Proto\Common\Account;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Account\BankAccount\Ach instead.
     * @deprecated
     */
    class BankAccount_Ach {}
}
class_exists(BankAccount\Ach::class);
@trigger_error('Io\Token\Proto\Common\Account\BankAccount_Ach is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Account\BankAccount\Ach instead', E_USER_DEPRECATED);

