<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Io\Token\Proto\Common\Account;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Account\BankAccount\Swift instead.
     * @deprecated
     */
    class BankAccount_Swift {}
}
class_exists(BankAccount\Swift::class);
@trigger_error('Io\Token\Proto\Common\Account\BankAccount_Swift is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Account\BankAccount\Swift instead', E_USER_DEPRECATED);

