<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Io\Token\Proto\Common\Account;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Account\BankAccount\Iban instead.
     * @deprecated
     */
    class BankAccount_Iban {}
}
class_exists(BankAccount\Iban::class);
@trigger_error('Io\Token\Proto\Common\Account\BankAccount_Iban is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Account\BankAccount\Iban instead', E_USER_DEPRECATED);

