<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto

namespace Io\Token\Proto\Common\Notification;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Metadata for a notification
 *
 * Generated from protobuf message <code>io.token.proto.common.notification.DeviceMetadata</code>
 */
class DeviceMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Name of the application to add keys to (e.g. Token, Chrome)
     *
     * Generated from protobuf field <code>string application = 1;</code>
     */
    private $application = '';
    /**
     * Application version (e.g. 2.0)
     *
     * Generated from protobuf field <code>string application_version = 2;</code>
     */
    private $application_version = '';
    /**
     * Device the application resides on (e.g. Mac, iPhone X), to support multiple devices
     *
     * Generated from protobuf field <code>string device = 3;</code>
     */
    private $device = '';
    /**
     * Longitude of the user's location to signal where the request is coming from
     *
     * Generated from protobuf field <code>double longitude = 4 [(.io.token.proto.extensions.field.redact) = true];</code>
     */
    private $longitude = 0.0;
    /**
     * Latitude of the user's location
     *
     * Generated from protobuf field <code>double latitude = 5 [(.io.token.proto.extensions.field.redact) = true];</code>
     */
    private $latitude = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $application
     *           Name of the application to add keys to (e.g. Token, Chrome)
     *     @type string $application_version
     *           Application version (e.g. 2.0)
     *     @type string $device
     *           Device the application resides on (e.g. Mac, iPhone X), to support multiple devices
     *     @type float $longitude
     *           Longitude of the user's location to signal where the request is coming from
     *     @type float $latitude
     *           Latitude of the user's location
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Notification::initOnce();
        parent::__construct($data);
    }

    /**
     * Name of the application to add keys to (e.g. Token, Chrome)
     *
     * Generated from protobuf field <code>string application = 1;</code>
     * @return string
     */
    public function getApplication()
    {
        return $this->application;
    }

    /**
     * Name of the application to add keys to (e.g. Token, Chrome)
     *
     * Generated from protobuf field <code>string application = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApplication($var)
    {
        GPBUtil::checkString($var, True);
        $this->application = $var;

        return $this;
    }

    /**
     * Application version (e.g. 2.0)
     *
     * Generated from protobuf field <code>string application_version = 2;</code>
     * @return string
     */
    public function getApplicationVersion()
    {
        return $this->application_version;
    }

    /**
     * Application version (e.g. 2.0)
     *
     * Generated from protobuf field <code>string application_version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setApplicationVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->application_version = $var;

        return $this;
    }

    /**
     * Device the application resides on (e.g. Mac, iPhone X), to support multiple devices
     *
     * Generated from protobuf field <code>string device = 3;</code>
     * @return string
     */
    public function getDevice()
    {
        return $this->device;
    }

    /**
     * Device the application resides on (e.g. Mac, iPhone X), to support multiple devices
     *
     * Generated from protobuf field <code>string device = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDevice($var)
    {
        GPBUtil::checkString($var, True);
        $this->device = $var;

        return $this;
    }

    /**
     * Longitude of the user's location to signal where the request is coming from
     *
     * Generated from protobuf field <code>double longitude = 4 [(.io.token.proto.extensions.field.redact) = true];</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Longitude of the user's location to signal where the request is coming from
     *
     * Generated from protobuf field <code>double longitude = 4 [(.io.token.proto.extensions.field.redact) = true];</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->longitude = $var;

        return $this;
    }

    /**
     * Latitude of the user's location
     *
     * Generated from protobuf field <code>double latitude = 5 [(.io.token.proto.extensions.field.redact) = true];</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Latitude of the user's location
     *
     * Generated from protobuf field <code>double latitude = 5 [(.io.token.proto.extensions.field.redact) = true];</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->latitude = $var;

        return $this;
    }

}

