<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: polishapi.proto

namespace Io\Token\Proto\Common\Providerspecific\Polishapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.providerspecific.polishapi.SenderRecipient</code>
 */
class SenderRecipient extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string account_number = 1;</code>
     */
    private $account_number = '';
    /**
     * Generated from protobuf field <code>string account_mass_payment = 2;</code>
     */
    private $account_mass_payment = '';
    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.Bank bank = 3;</code>
     */
    private $bank = null;
    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.NameAddress name_address = 4;</code>
     */
    private $name_address = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $account_number
     *     @type string $account_mass_payment
     *     @type \Io\Token\Proto\Common\Providerspecific\Polishapi\Bank $bank
     *     @type \Io\Token\Proto\Common\Providerspecific\Polishapi\NameAddress $name_address
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Polishapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string account_number = 1;</code>
     * @return string
     */
    public function getAccountNumber()
    {
        return $this->account_number;
    }

    /**
     * Generated from protobuf field <code>string account_number = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string account_mass_payment = 2;</code>
     * @return string
     */
    public function getAccountMassPayment()
    {
        return $this->account_mass_payment;
    }

    /**
     * Generated from protobuf field <code>string account_mass_payment = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountMassPayment($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_mass_payment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.Bank bank = 3;</code>
     * @return \Io\Token\Proto\Common\Providerspecific\Polishapi\Bank
     */
    public function getBank()
    {
        return $this->bank;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.Bank bank = 3;</code>
     * @param \Io\Token\Proto\Common\Providerspecific\Polishapi\Bank $var
     * @return $this
     */
    public function setBank($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Providerspecific\Polishapi\Bank::class);
        $this->bank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.NameAddress name_address = 4;</code>
     * @return \Io\Token\Proto\Common\Providerspecific\Polishapi\NameAddress
     */
    public function getNameAddress()
    {
        return $this->name_address;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.NameAddress name_address = 4;</code>
     * @param \Io\Token\Proto\Common\Providerspecific\Polishapi\NameAddress $var
     * @return $this
     */
    public function setNameAddress($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Providerspecific\Polishapi\NameAddress::class);
        $this->name_address = $var;

        return $this;
    }

}

