<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: provider/polishapi.proto

namespace Io\Token\Proto\Common\Providerspecific\Polishapi;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.providerspecific.polishapi.TransactionInfoTax</code>
 */
class TransactionInfoTax extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.Payer payer_info = 1;</code>
     */
    private $payer_info = null;
    /**
     * Generated from protobuf field <code>string form_code = 2;</code>
     */
    private $form_code = '';
    /**
     * Generated from protobuf field <code>string period_id = 3;</code>
     */
    private $period_id = '';
    /**
     * Generated from protobuf field <code>string period_type = 4;</code>
     */
    private $period_type = '';
    /**
     * Generated from protobuf field <code>int32 year = 5;</code>
     */
    private $year = 0;
    /**
     * Generated from protobuf field <code>string obligation_id = 6;</code>
     */
    private $obligation_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Providerspecific\Polishapi\Payer $payer_info
     *     @type string $form_code
     *     @type string $period_id
     *     @type string $period_type
     *     @type int $year
     *     @type string $obligation_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Provider\Polishapi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.Payer payer_info = 1;</code>
     * @return \Io\Token\Proto\Common\Providerspecific\Polishapi\Payer
     */
    public function getPayerInfo()
    {
        return $this->payer_info;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.Payer payer_info = 1;</code>
     * @param \Io\Token\Proto\Common\Providerspecific\Polishapi\Payer $var
     * @return $this
     */
    public function setPayerInfo($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Providerspecific\Polishapi\Payer::class);
        $this->payer_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string form_code = 2;</code>
     * @return string
     */
    public function getFormCode()
    {
        return $this->form_code;
    }

    /**
     * Generated from protobuf field <code>string form_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFormCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->form_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string period_id = 3;</code>
     * @return string
     */
    public function getPeriodId()
    {
        return $this->period_id;
    }

    /**
     * Generated from protobuf field <code>string period_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPeriodId($var)
    {
        GPBUtil::checkString($var, True);
        $this->period_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string period_type = 4;</code>
     * @return string
     */
    public function getPeriodType()
    {
        return $this->period_type;
    }

    /**
     * Generated from protobuf field <code>string period_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPeriodType($var)
    {
        GPBUtil::checkString($var, True);
        $this->period_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 year = 5;</code>
     * @return int
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Generated from protobuf field <code>int32 year = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setYear($var)
    {
        GPBUtil::checkInt32($var);
        $this->year = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string obligation_id = 6;</code>
     * @return string
     */
    public function getObligationId()
    {
        return $this->obligation_id;
    }

    /**
     * Generated from protobuf field <code>string obligation_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setObligationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->obligation_id = $var;

        return $this;
    }

}

