<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.GetTransactionsResponse</code>
 */
class GetTransactionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * transaction details
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.transaction.Transaction transactions = 1;</code>
     */
    private $transactions;
    /**
     * Optional offset state for the client to roundtrip.
     *
     * Generated from protobuf field <code>string offset = 2;</code>
     */
    private $offset = '';
    /**
     * Generated from protobuf field <code>.io.token.proto.common.transaction.RequestStatus status = 3;</code>
     */
    private $status = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Transaction\Transaction[]|\Google\Protobuf\Internal\RepeatedField $transactions
     *           transaction details
     *     @type string $offset
     *           Optional offset state for the client to roundtrip.
     *     @type int $status
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * transaction details
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.transaction.Transaction transactions = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * transaction details
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.transaction.Transaction transactions = 1;</code>
     * @param \Io\Token\Proto\Common\Transaction\Transaction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Token\Proto\Common\Transaction\Transaction::class);
        $this->transactions = $arr;

        return $this;
    }

    /**
     * Optional offset state for the client to roundtrip.
     *
     * Generated from protobuf field <code>string offset = 2;</code>
     * @return string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Optional offset state for the client to roundtrip.
     *
     * Generated from protobuf field <code>string offset = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkString($var, True);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.transaction.RequestStatus status = 3;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.transaction.RequestStatus status = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Io\Token\Proto\Common\Transaction\RequestStatus::class);
        $this->status = $var;

        return $this;
    }

}

