<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Gateway\GetTokensRequest\Type instead.
     * @deprecated
     */
    class GetTokensRequest_Type {}
}
class_exists(GetTokensRequest\Type::class);
@trigger_error('Io\Token\Proto\Gateway\GetTokensRequest_Type is deprecated and will be removed in the next major release. Use Io\Token\Proto\Gateway\GetTokensRequest\Type instead', E_USER_DEPRECATED);

