<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.SubscribeToNotificationsRequest</code>
 */
class SubscribeToNotificationsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Who is sending the notification
     *
     * Generated from protobuf field <code>string handler = 1;</code>
     */
    private $handler = '';
    /**
     * Available to handler when sending notifications
     *
     * Generated from protobuf field <code>map<string, string> handler_instructions = 2;</code>
     */
    private $handler_instructions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $handler
     *           Who is sending the notification
     *     @type array|\Google\Protobuf\Internal\MapField $handler_instructions
     *           Available to handler when sending notifications
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * Who is sending the notification
     *
     * Generated from protobuf field <code>string handler = 1;</code>
     * @return string
     */
    public function getHandler()
    {
        return $this->handler;
    }

    /**
     * Who is sending the notification
     *
     * Generated from protobuf field <code>string handler = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHandler($var)
    {
        GPBUtil::checkString($var, True);
        $this->handler = $var;

        return $this;
    }

    /**
     * Available to handler when sending notifications
     *
     * Generated from protobuf field <code>map<string, string> handler_instructions = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getHandlerInstructions()
    {
        return $this->handler_instructions;
    }

    /**
     * Available to handler when sending notifications
     *
     * Generated from protobuf field <code>map<string, string> handler_instructions = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setHandlerInstructions($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->handler_instructions = $arr;

        return $this;
    }

}

