<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer.proto

namespace Io\Token\Proto\Common\Transfer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.transfer.BulkTransfer</code>
 */
class BulkTransfer extends \Google\Protobuf\Internal\Message
{
    /**
     * Token ID computed as the hash of the token payload
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string token_id = 2;</code>
     */
    private $token_id = '';
    /**
     * Generated from protobuf field <code>int64 created_at_ms = 3;</code>
     */
    private $created_at_ms = 0;
    /**
     * Transactions for which the bank provides IDs and/or statuses.
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.transfer.BulkTransfer.Transaction transactions = 4;</code>
     */
    private $transactions;
    /**
     * Might not be populated right away.
     *
     * Generated from protobuf field <code>string total_amount = 5;</code>
     */
    private $total_amount = '';
    /**
     * Generated from protobuf field <code>.io.token.proto.common.transferinstructions.TransferEndpoint source = 6;</code>
     */
    private $source = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Token ID computed as the hash of the token payload
     *     @type string $token_id
     *     @type int|string $created_at_ms
     *     @type \Io\Token\Proto\Common\Transfer\BulkTransfer\Transaction[]|\Google\Protobuf\Internal\RepeatedField $transactions
     *           Transactions for which the bank provides IDs and/or statuses.
     *     @type string $total_amount
     *           Might not be populated right away.
     *     @type \Io\Token\Proto\Common\Transferinstructions\TransferEndpoint $source
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transfer::initOnce();
        parent::__construct($data);
    }

    /**
     * Token ID computed as the hash of the token payload
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Token ID computed as the hash of the token payload
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string token_id = 2;</code>
     * @return string
     */
    public function getTokenId()
    {
        return $this->token_id;
    }

    /**
     * Generated from protobuf field <code>string token_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->token_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 created_at_ms = 3;</code>
     * @return int|string
     */
    public function getCreatedAtMs()
    {
        return $this->created_at_ms;
    }

    /**
     * Generated from protobuf field <code>int64 created_at_ms = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreatedAtMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->created_at_ms = $var;

        return $this;
    }

    /**
     * Transactions for which the bank provides IDs and/or statuses.
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.transfer.BulkTransfer.Transaction transactions = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * Transactions for which the bank provides IDs and/or statuses.
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.transfer.BulkTransfer.Transaction transactions = 4;</code>
     * @param \Io\Token\Proto\Common\Transfer\BulkTransfer\Transaction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Token\Proto\Common\Transfer\BulkTransfer\Transaction::class);
        $this->transactions = $arr;

        return $this;
    }

    /**
     * Might not be populated right away.
     *
     * Generated from protobuf field <code>string total_amount = 5;</code>
     * @return string
     */
    public function getTotalAmount()
    {
        return $this->total_amount;
    }

    /**
     * Might not be populated right away.
     *
     * Generated from protobuf field <code>string total_amount = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTotalAmount($var)
    {
        GPBUtil::checkString($var, True);
        $this->total_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.transferinstructions.TransferEndpoint source = 6;</code>
     * @return \Io\Token\Proto\Common\Transferinstructions\TransferEndpoint
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.transferinstructions.TransferEndpoint source = 6;</code>
     * @param \Io\Token\Proto\Common\Transferinstructions\TransferEndpoint $var
     * @return $this
     */
    public function setSource($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Transferinstructions\TransferEndpoint::class);
        $this->source = $var;

        return $this;
    }

}

