<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer.proto

namespace Io\Token\Proto\Common\Transfer;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Transfer\Transfer\Method instead.
     * @deprecated
     */
    class Transfer_Method {}
}
class_exists(Transfer\Method::class);
@trigger_error('Io\Token\Proto\Common\Transfer\Transfer_Method is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Transfer\Transfer\Method instead', E_USER_DEPRECATED);

