<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consent.proto

namespace Io\Token\Proto\Common\Consent;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Consent\Consent\BulkPayment instead.
     * @deprecated
     */
    class Consent_BulkPayment {}
}
class_exists(Consent\BulkPayment::class);
@trigger_error('Io\Token\Proto\Common\Consent\Consent_BulkPayment is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Consent\Consent\BulkPayment instead', E_USER_DEPRECATED);

