<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consent.proto

namespace Io\Token\Proto\Common\Consent;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Consent\Consent\InformationAccess\ResourceAccess\ResourceType instead.
     * @deprecated
     */
    class Consent_InformationAccess_ResourceAccess_ResourceType {}
}
class_exists(Consent\InformationAccess\ResourceAccess\ResourceType::class);
@trigger_error('Io\Token\Proto\Common\Consent\Consent_InformationAccess_ResourceAccess_ResourceType is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Consent\Consent\InformationAccess\ResourceAccess\ResourceType instead', E_USER_DEPRECATED);

