<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consent.proto

namespace Io\Token\Proto\Common\Consent;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.consent.ConsentRequest</code>
 */
class ConsentRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tpp_name = 1;</code>
     */
    private $tpp_name = '';
    /**
     * Generated from protobuf field <code>string tpp_callback_url = 2;</code>
     */
    private $tpp_callback_url = '';
    /**
     * Generated from protobuf field <code>string tpp_ref_id = 3;</code>
     */
    private $tpp_ref_id = '';
    /**
     * Generated from protobuf field <code>string description = 4;</code>
     */
    private $description = '';
    protected $body;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tpp_name
     *     @type string $tpp_callback_url
     *     @type string $tpp_ref_id
     *     @type string $description
     *     @type \Io\Token\Proto\Common\Token\TokenRequestPayload\AccessBody\ResourceTypeList $resource_type_list
     *     @type \Io\Token\Proto\Common\Token\TokenRequestPayload\AccessBody\AccountResourceList $account_resource_list
     *     @type \Io\Token\Proto\Common\Token\TokenRequestPayload\TransferBody $transfer_body
     *     @type \Io\Token\Proto\Common\Token\StandingOrderBody $standing_order_body
     *     @type \Io\Token\Proto\Common\Token\BulkTransferBody $bulk_transfer_body
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Consent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tpp_name = 1;</code>
     * @return string
     */
    public function getTppName()
    {
        return $this->tpp_name;
    }

    /**
     * Generated from protobuf field <code>string tpp_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTppName($var)
    {
        GPBUtil::checkString($var, True);
        $this->tpp_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tpp_callback_url = 2;</code>
     * @return string
     */
    public function getTppCallbackUrl()
    {
        return $this->tpp_callback_url;
    }

    /**
     * Generated from protobuf field <code>string tpp_callback_url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTppCallbackUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->tpp_callback_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tpp_ref_id = 3;</code>
     * @return string
     */
    public function getTppRefId()
    {
        return $this->tpp_ref_id;
    }

    /**
     * Generated from protobuf field <code>string tpp_ref_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTppRefId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tpp_ref_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenRequestPayload.AccessBody.ResourceTypeList resource_type_list = 5;</code>
     * @return \Io\Token\Proto\Common\Token\TokenRequestPayload\AccessBody\ResourceTypeList
     */
    public function getResourceTypeList()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenRequestPayload.AccessBody.ResourceTypeList resource_type_list = 5;</code>
     * @param \Io\Token\Proto\Common\Token\TokenRequestPayload\AccessBody\ResourceTypeList $var
     * @return $this
     */
    public function setResourceTypeList($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Token\TokenRequestPayload_AccessBody_ResourceTypeList::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenRequestPayload.AccessBody.AccountResourceList account_resource_list = 6;</code>
     * @return \Io\Token\Proto\Common\Token\TokenRequestPayload\AccessBody\AccountResourceList
     */
    public function getAccountResourceList()
    {
        return $this->readOneof(6);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenRequestPayload.AccessBody.AccountResourceList account_resource_list = 6;</code>
     * @param \Io\Token\Proto\Common\Token\TokenRequestPayload\AccessBody\AccountResourceList $var
     * @return $this
     */
    public function setAccountResourceList($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Token\TokenRequestPayload_AccessBody_AccountResourceList::class);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenRequestPayload.TransferBody transfer_body = 7;</code>
     * @return \Io\Token\Proto\Common\Token\TokenRequestPayload\TransferBody
     */
    public function getTransferBody()
    {
        return $this->readOneof(7);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenRequestPayload.TransferBody transfer_body = 7;</code>
     * @param \Io\Token\Proto\Common\Token\TokenRequestPayload\TransferBody $var
     * @return $this
     */
    public function setTransferBody($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Token\TokenRequestPayload_TransferBody::class);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.StandingOrderBody standing_order_body = 8;</code>
     * @return \Io\Token\Proto\Common\Token\StandingOrderBody
     */
    public function getStandingOrderBody()
    {
        return $this->readOneof(8);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.StandingOrderBody standing_order_body = 8;</code>
     * @param \Io\Token\Proto\Common\Token\StandingOrderBody $var
     * @return $this
     */
    public function setStandingOrderBody($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Token\StandingOrderBody::class);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.BulkTransferBody bulk_transfer_body = 9;</code>
     * @return \Io\Token\Proto\Common\Token\BulkTransferBody
     */
    public function getBulkTransferBody()
    {
        return $this->readOneof(9);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.BulkTransferBody bulk_transfer_body = 9;</code>
     * @param \Io\Token\Proto\Common\Token\BulkTransferBody $var
     * @return $this
     */
    public function setBulkTransferBody($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Token\BulkTransferBody::class);
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getBody()
    {
        return $this->whichOneof("body");
    }

}

