<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consent.proto

namespace Io\Token\Proto\Common\Consent;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Consent\CreateConsent\AccountResourceAccess instead.
     * @deprecated
     */
    class CreateConsent_AccountResourceAccess {}
}
class_exists(CreateConsent\AccountResourceAccess::class);
@trigger_error('Io\Token\Proto\Common\Consent\CreateConsent_AccountResourceAccess is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Consent\CreateConsent\AccountResourceAccess instead', E_USER_DEPRECATED);

