<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consent.proto

namespace Io\Token\Proto\Common\Consent;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Consent\CreateConsent\ResourceTypeAccess instead.
     * @deprecated
     */
    class CreateConsent_ResourceTypeAccess {}
}
class_exists(CreateConsent\ResourceTypeAccess::class);
@trigger_error('Io\Token\Proto\Common\Consent\CreateConsent_ResourceTypeAccess is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Consent\CreateConsent\ResourceTypeAccess instead', E_USER_DEPRECATED);

