<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consent.proto

namespace Io\Token\Proto\Common\Consent;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Consent\CreateConsent\BulkTransfer instead.
     * @deprecated
     */
    class CreateConsent_BulkTransfer {}
}
class_exists(CreateConsent\BulkTransfer::class);
@trigger_error('Io\Token\Proto\Common\Consent\CreateConsent_BulkTransfer is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Consent\CreateConsent\BulkTransfer instead', E_USER_DEPRECATED);

