<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: provider/stet.proto

namespace Io\Token\Proto\Common\Providerspecific\Stet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.providerspecific.stet.StetTransferMetadata</code>
 */
class StetTransferMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.stet.PaymentTypeInformation payment_type_information = 1;</code>
     */
    private $payment_type_information = null;
    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.stet.FinancialInstitutionIdentification debtor_agent = 2;</code>
     */
    private $debtor_agent = null;
    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.stet.Beneficiary beneficiary = 3;</code>
     */
    private $beneficiary = null;
    /**
     * Generated from protobuf field <code>string end_to_end_id = 4;</code>
     */
    private $end_to_end_id = '';
    /**
     * Execution date shifting rule for standing orders.This data attribute defines the behaviour when recurring payment dates falls on a weekend or bank holiday. FWNG: following, PREC: preceding.
     *
     * Generated from protobuf field <code>string execution_rule = 5;</code>
     */
    private $execution_rule = '';
    /**
     * List of needed regulatory reporting codes for international payments
     *
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.stet.RegulatoryReportingCodes regulatory_reporting_codes = 6;</code>
     */
    private $regulatory_reporting_codes = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Providerspecific\Stet\PaymentTypeInformation $payment_type_information
     *     @type \Io\Token\Proto\Common\Providerspecific\Stet\FinancialInstitutionIdentification $debtor_agent
     *     @type \Io\Token\Proto\Common\Providerspecific\Stet\Beneficiary $beneficiary
     *     @type string $end_to_end_id
     *     @type string $execution_rule
     *           Execution date shifting rule for standing orders.This data attribute defines the behaviour when recurring payment dates falls on a weekend or bank holiday. FWNG: following, PREC: preceding.
     *     @type \Io\Token\Proto\Common\Providerspecific\Stet\RegulatoryReportingCodes $regulatory_reporting_codes
     *           List of needed regulatory reporting codes for international payments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Provider\Stet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.stet.PaymentTypeInformation payment_type_information = 1;</code>
     * @return \Io\Token\Proto\Common\Providerspecific\Stet\PaymentTypeInformation
     */
    public function getPaymentTypeInformation()
    {
        return $this->payment_type_information;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.stet.PaymentTypeInformation payment_type_information = 1;</code>
     * @param \Io\Token\Proto\Common\Providerspecific\Stet\PaymentTypeInformation $var
     * @return $this
     */
    public function setPaymentTypeInformation($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Providerspecific\Stet\PaymentTypeInformation::class);
        $this->payment_type_information = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.stet.FinancialInstitutionIdentification debtor_agent = 2;</code>
     * @return \Io\Token\Proto\Common\Providerspecific\Stet\FinancialInstitutionIdentification
     */
    public function getDebtorAgent()
    {
        return $this->debtor_agent;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.stet.FinancialInstitutionIdentification debtor_agent = 2;</code>
     * @param \Io\Token\Proto\Common\Providerspecific\Stet\FinancialInstitutionIdentification $var
     * @return $this
     */
    public function setDebtorAgent($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Providerspecific\Stet\FinancialInstitutionIdentification::class);
        $this->debtor_agent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.stet.Beneficiary beneficiary = 3;</code>
     * @return \Io\Token\Proto\Common\Providerspecific\Stet\Beneficiary
     */
    public function getBeneficiary()
    {
        return $this->beneficiary;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.stet.Beneficiary beneficiary = 3;</code>
     * @param \Io\Token\Proto\Common\Providerspecific\Stet\Beneficiary $var
     * @return $this
     */
    public function setBeneficiary($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Providerspecific\Stet\Beneficiary::class);
        $this->beneficiary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string end_to_end_id = 4;</code>
     * @return string
     */
    public function getEndToEndId()
    {
        return $this->end_to_end_id;
    }

    /**
     * Generated from protobuf field <code>string end_to_end_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setEndToEndId($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_to_end_id = $var;

        return $this;
    }

    /**
     * Execution date shifting rule for standing orders.This data attribute defines the behaviour when recurring payment dates falls on a weekend or bank holiday. FWNG: following, PREC: preceding.
     *
     * Generated from protobuf field <code>string execution_rule = 5;</code>
     * @return string
     */
    public function getExecutionRule()
    {
        return $this->execution_rule;
    }

    /**
     * Execution date shifting rule for standing orders.This data attribute defines the behaviour when recurring payment dates falls on a weekend or bank holiday. FWNG: following, PREC: preceding.
     *
     * Generated from protobuf field <code>string execution_rule = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setExecutionRule($var)
    {
        GPBUtil::checkString($var, True);
        $this->execution_rule = $var;

        return $this;
    }

    /**
     * List of needed regulatory reporting codes for international payments
     *
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.stet.RegulatoryReportingCodes regulatory_reporting_codes = 6;</code>
     * @return \Io\Token\Proto\Common\Providerspecific\Stet\RegulatoryReportingCodes
     */
    public function getRegulatoryReportingCodes()
    {
        return $this->regulatory_reporting_codes;
    }

    /**
     * List of needed regulatory reporting codes for international payments
     *
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.stet.RegulatoryReportingCodes regulatory_reporting_codes = 6;</code>
     * @param \Io\Token\Proto\Common\Providerspecific\Stet\RegulatoryReportingCodes $var
     * @return $this
     */
    public function setRegulatoryReportingCodes($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Providerspecific\Stet\RegulatoryReportingCodes::class);
        $this->regulatory_reporting_codes = $var;

        return $this;
    }

}

