<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: provider/stet.proto

namespace Io\Token\Proto\Common\Providerspecific\Stet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.providerspecific.stet.StetTransactionDetails</code>
 */
class StetTransactionDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Technical incremental identification of the transaction.
     *
     * Generated from protobuf field <code>string entry_reference = 1;</code>
     */
    private $entry_reference = '';
    /**
     * Generated from protobuf field <code>string value_date = 2;</code>
     */
    private $value_date = '';
    /**
     * Date used for specific purposes:
     * for card transaction: date of the transaction;
     * for credit transfer: acquiring date of the transaction;
     * for direct debit: receiving date of the transaction.
     *
     * Generated from protobuf field <code>string transaction_date = 3;</code>
     */
    private $transaction_date = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $entry_reference
     *           Technical incremental identification of the transaction.
     *     @type string $value_date
     *     @type string $transaction_date
     *           Date used for specific purposes:
     *           for card transaction: date of the transaction;
     *           for credit transfer: acquiring date of the transaction;
     *           for direct debit: receiving date of the transaction.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Provider\Stet::initOnce();
        parent::__construct($data);
    }

    /**
     * Technical incremental identification of the transaction.
     *
     * Generated from protobuf field <code>string entry_reference = 1;</code>
     * @return string
     */
    public function getEntryReference()
    {
        return $this->entry_reference;
    }

    /**
     * Technical incremental identification of the transaction.
     *
     * Generated from protobuf field <code>string entry_reference = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEntryReference($var)
    {
        GPBUtil::checkString($var, True);
        $this->entry_reference = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value_date = 2;</code>
     * @return string
     */
    public function getValueDate()
    {
        return $this->value_date;
    }

    /**
     * Generated from protobuf field <code>string value_date = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValueDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->value_date = $var;

        return $this;
    }

    /**
     * Date used for specific purposes:
     * for card transaction: date of the transaction;
     * for credit transfer: acquiring date of the transaction;
     * for direct debit: receiving date of the transaction.
     *
     * Generated from protobuf field <code>string transaction_date = 3;</code>
     * @return string
     */
    public function getTransactionDate()
    {
        return $this->transaction_date;
    }

    /**
     * Date used for specific purposes:
     * for card transaction: date of the transaction;
     * for credit transfer: acquiring date of the transaction;
     * for direct debit: receiving date of the transaction.
     *
     * Generated from protobuf field <code>string transaction_date = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_date = $var;

        return $this;
    }

}

