<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: submission.proto

namespace Io\Token\Proto\Common\Submission;

/**
 * Status of an instruction sent to the bank, e.g. of a payment or standing order.
 *
 * Protobuf type <code>io.token.proto.common.submission.SubmissionStatus</code>
 */
class SubmissionStatus
{
    /**
     * Invalid status
     *
     * Generated from protobuf enum <code>INVALID = 0;</code>
     */
    const INVALID = 0;
    /**
     * Pending submission by Token.
     *
     * Generated from protobuf enum <code>PENDING = 1;</code>
     */
    const PENDING = 1;
    /**
     * Submitted by Token; pending submission by the bank.
     *
     * Generated from protobuf enum <code>PROCESSING = 2;</code>
     */
    const PROCESSING = 2;
    /**
     * Submission successful.
     *
     * Generated from protobuf enum <code>SUCCESS = 3;</code>
     */
    const SUCCESS = 3;
    /**
     * Submission failed.
     *
     * Generated from protobuf enum <code>FAILED = 4;</code>
     */
    const FAILED = 4;
    /**
     * Submission acknowledged by the bank, but unable retrieve further status.
     *
     * Generated from protobuf enum <code>INITIATED = 5;</code>
     */
    const INITIATED = 5;
    /**
     * Generated from protobuf enum <code>CANCELED = 6;</code>
     */
    const CANCELED = 6;
    /**
     * Sent to the bank but not acknowledged by the bank.
     *
     * Generated from protobuf enum <code>SENT = 7;</code>
     */
    const SENT = 7;
    /**
     * Requires authorization by the user to complete
     *
     * Generated from protobuf enum <code>PENDING_EXTERNAL_AUTHORIZATION = 8;</code>
     */
    const PENDING_EXTERNAL_AUTHORIZATION = 8;
}

