<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto

namespace Io\Token\Proto\Common\Token;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Token\Policy\SingleSignature instead.
     * @deprecated
     */
    class Policy_SingleSignature {}
}
class_exists(Policy\SingleSignature::class);
@trigger_error('Io\Token\Proto\Common\Token\Policy_SingleSignature is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Token\Policy\SingleSignature instead', E_USER_DEPRECATED);

