<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto

namespace Io\Token\Proto\Common\Token;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Token\TokenRequestPayload\AccessBody\ResourceType instead.
     * @deprecated
     */
    class TokenRequestPayload_AccessBody_ResourceType {}
}
class_exists(TokenRequestPayload\AccessBody\ResourceType::class);
@trigger_error('Io\Token\Proto\Common\Token\TokenRequestPayload_AccessBody_ResourceType is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Token\TokenRequestPayload\AccessBody\ResourceType instead', E_USER_DEPRECATED);

