<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto

namespace Io\Token\Proto\Common\Token;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generic token envelope definition.
 *
 * Generated from protobuf message <code>io.token.proto.common.token.Token</code>
 */
class Token extends \Google\Protobuf\Internal\Message
{
    /**
     * Computed as sha(token).
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Token payload, being signed.
     *
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenPayload payload = 2;</code>
     */
    private $payload = null;
    /**
     * Payload signatures.
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.token.TokenSignature payload_signatures = 3;</code>
     */
    private $payload_signatures;
    /**
     * ID of the latest token replacing it
     *
     * Generated from protobuf field <code>string replaced_by_token_id = 4;</code>
     */
    private $replaced_by_token_id = '';
    /**
     * ID of the token request associated with the token (optional)
     *
     * Generated from protobuf field <code>string token_request_id = 5;</code>
     */
    private $token_request_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Computed as sha(token).
     *     @type \Io\Token\Proto\Common\Token\TokenPayload $payload
     *           Token payload, being signed.
     *     @type \Io\Token\Proto\Common\Token\TokenSignature[]|\Google\Protobuf\Internal\RepeatedField $payload_signatures
     *           Payload signatures.
     *     @type string $replaced_by_token_id
     *           ID of the latest token replacing it
     *     @type string $token_request_id
     *           ID of the token request associated with the token (optional)
     * }
     */
    public function __construct($data = NULL) {
        \Io\Token\GPBMetadata\Token::initOnce();
        parent::__construct($data);
    }

    /**
     * Computed as sha(token).
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Computed as sha(token).
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Token payload, being signed.
     *
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenPayload payload = 2;</code>
     * @return \Io\Token\Proto\Common\Token\TokenPayload
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Token payload, being signed.
     *
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenPayload payload = 2;</code>
     * @param \Io\Token\Proto\Common\Token\TokenPayload $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Token\TokenPayload::class);
        $this->payload = $var;

        return $this;
    }

    /**
     * Payload signatures.
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.token.TokenSignature payload_signatures = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPayloadSignatures()
    {
        return $this->payload_signatures;
    }

    /**
     * Payload signatures.
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.token.TokenSignature payload_signatures = 3;</code>
     * @param \Io\Token\Proto\Common\Token\TokenSignature[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPayloadSignatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Token\Proto\Common\Token\TokenSignature::class);
        $this->payload_signatures = $arr;

        return $this;
    }

    /**
     * ID of the latest token replacing it
     *
     * Generated from protobuf field <code>string replaced_by_token_id = 4;</code>
     * @return string
     */
    public function getReplacedByTokenId()
    {
        return $this->replaced_by_token_id;
    }

    /**
     * ID of the latest token replacing it
     *
     * Generated from protobuf field <code>string replaced_by_token_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setReplacedByTokenId($var)
    {
        GPBUtil::checkString($var, True);
        $this->replaced_by_token_id = $var;

        return $this;
    }

    /**
     * ID of the token request associated with the token (optional)
     *
     * Generated from protobuf field <code>string token_request_id = 5;</code>
     * @return string
     */
    public function getTokenRequestId()
    {
        return $this->token_request_id;
    }

    /**
     * ID of the token request associated with the token (optional)
     *
     * Generated from protobuf field <code>string token_request_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTokenRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->token_request_id = $var;

        return $this;
    }

}

