<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto

namespace Io\Token\Proto\Common\Token;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.token.TokenSignature</code>
 */
class TokenSignature extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenSignature.Action action = 1;</code>
     */
    private $action = 0;
    /**
     * Generated from protobuf field <code>.io.token.proto.common.security.Signature signature = 2;</code>
     */
    private $signature = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $action
     *     @type \Io\Token\Proto\Common\Security\Signature $signature
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Token::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenSignature.Action action = 1;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenSignature.Action action = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \Io\Token\Proto\Common\Token\TokenSignature_Action::class);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.security.Signature signature = 2;</code>
     * @return \Io\Token\Proto\Common\Security\Signature
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.security.Signature signature = 2;</code>
     * @param \Io\Token\Proto\Common\Security\Signature $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Security\Signature::class);
        $this->signature = $var;

        return $this;
    }

}

