<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto

namespace Io\Token\Proto\Common\Token;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Token\TokenRequestPayload\AccessBody\AccountResourceType instead.
     * @deprecated
     */
    class TokenRequestPayload_AccessBody_AccountResourceType {}
}
class_exists(TokenRequestPayload\AccessBody\AccountResourceType::class);
@trigger_error('Io\Token\Proto\Common\Token\TokenRequestPayload_AccessBody_AccountResourceType is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Token\TokenRequestPayload\AccessBody\AccountResourceType instead', E_USER_DEPRECATED);

