<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsp/bankconfig.proto

namespace Io\Token\Proto\Common\Tsp\Bankconfig\RegistrationPayload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.tsp.bankconfig.RegistrationPayload.UKOpenBankingStandard</code>
 */
class UKOpenBankingStandard extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ssa = 1;</code>
     */
    private $ssa = '';
    /**
     * Generated from protobuf field <code>string signing_key_id = 2;</code>
     */
    private $signing_key_id = '';
    /**
     * Generated from protobuf field <code>string transport_key_id = 3;</code>
     */
    private $transport_key_id = '';
    /**
     * only required when there are multiple signing keys in the
     *
     * Generated from protobuf field <code>string jwt_signing_key_id = 4;</code>
     */
    private $jwt_signing_key_id = '';
    /**
     * software statement
     *
     * Generated from protobuf field <code>bool is_eidas = 5;</code>
     */
    private $is_eidas = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ssa
     *     @type string $signing_key_id
     *     @type string $transport_key_id
     *     @type string $jwt_signing_key_id
     *           only required when there are multiple signing keys in the
     *     @type bool $is_eidas
     *           software statement
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tsp\Bankconfig::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ssa = 1;</code>
     * @return string
     */
    public function getSsa()
    {
        return $this->ssa;
    }

    /**
     * Generated from protobuf field <code>string ssa = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSsa($var)
    {
        GPBUtil::checkString($var, True);
        $this->ssa = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string signing_key_id = 2;</code>
     * @return string
     */
    public function getSigningKeyId()
    {
        return $this->signing_key_id;
    }

    /**
     * Generated from protobuf field <code>string signing_key_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSigningKeyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->signing_key_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transport_key_id = 3;</code>
     * @return string
     */
    public function getTransportKeyId()
    {
        return $this->transport_key_id;
    }

    /**
     * Generated from protobuf field <code>string transport_key_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTransportKeyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transport_key_id = $var;

        return $this;
    }

    /**
     * only required when there are multiple signing keys in the
     *
     * Generated from protobuf field <code>string jwt_signing_key_id = 4;</code>
     * @return string
     */
    public function getJwtSigningKeyId()
    {
        return $this->jwt_signing_key_id;
    }

    /**
     * only required when there are multiple signing keys in the
     *
     * Generated from protobuf field <code>string jwt_signing_key_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setJwtSigningKeyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->jwt_signing_key_id = $var;

        return $this;
    }

    /**
     * software statement
     *
     * Generated from protobuf field <code>bool is_eidas = 5;</code>
     * @return bool
     */
    public function getIsEidas()
    {
        return $this->is_eidas;
    }

    /**
     * software statement
     *
     * Generated from protobuf field <code>bool is_eidas = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsEidas($var)
    {
        GPBUtil::checkBool($var);
        $this->is_eidas = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UKOpenBankingStandard::class, \Io\Token\Proto\Common\Tsp\Bankconfig\RegistrationPayload_UKOpenBankingStandard::class);

