<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banklink.proto

namespace GPBMetadata;

class Banklink
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Security::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acf020a0e62616e6b6c696e6b2e70726f746f1217696f2e746f6b656e2e" .
            "70726f746f2e62616e6b6c696e6b22650a1142616e6b417574686f72697a" .
            "6174696f6e120f0a0762616e6b5f6964180120012809123f0a086163636f" .
            "756e747318022003280b322d2e696f2e746f6b656e2e70726f746f2e636f" .
            "6d6d6f6e2e73656375726974792e5365616c65644d657373616765223f0a" .
            "164f6175746842616e6b417574686f72697a6174696f6e120f0a0762616e" .
            "6b5f696418012001280912140a0c6163636573735f746f6b656e18022001" .
            "28092a590a144163636f756e744c696e6b696e67537461747573120b0a07" .
            "494e56414c49441000120b0a0753554343455353100112270a234641494c" .
            "5552455f42414e4b5f415554484f52495a4154494f4e5f52455155495245" .
            "4410024219aa0216546f6b656e696f2e50726f746f2e42616e6b4c696e6b" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

