<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscriber.proto

namespace Io\Token\GPBMetadata;

class Subscriber
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5020a10737562736372696265722e70726f746f1220696f2e746f6b65" .
            "6e2e70726f746f2e636f6d6d6f6e2e7375627363726962657222ca010a0a" .
            "53756273637269626572120a0a026964180120012809120f0a0768616e64" .
            "6c657218022001280912630a1468616e646c65725f696e73747275637469" .
            "6f6e7318032003280b32452e696f2e746f6b656e2e70726f746f2e636f6d" .
            "6d6f6e2e737562736372696265722e537562736372696265722e48616e64" .
            "6c6572496e737472756374696f6e73456e7472791a3a0a1848616e646c65" .
            "72496e737472756374696f6e73456e747279120b0a036b65791801200128" .
            "09120d0a0576616c75651802200128093a023801423a4210537562736372" .
            "6962657250726f746f73aa0225546f6b656e696f2e50726f746f2e436f6d" .
            "6d6f6e2e5375627363726962657250726f746f73620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

