<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway\GetBankDowntimeReportResponse\BankDowntimeSummary;

/**
 * Protobuf type <code>io.token.proto.gateway.GetBankDowntimeReportResponse.BankDowntimeSummary.RequestType</code>
 */
class RequestType
{
    /**
     * Generated from protobuf enum <code>INVALID = 0;</code>
     */
    const INVALID = 0;
    /**
     * Generated from protobuf enum <code>AIS = 1;</code>
     */
    const AIS = 1;
    /**
     * Generated from protobuf enum <code>PIS = 2;</code>
     */
    const PIS = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(RequestType::class, \Io\Token\Proto\Gateway\GetBankDowntimeReportResponse_BankDowntimeSummary_RequestType::class);

