<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: providerspecific.proto

namespace Io\Token\Proto\Common\Providerspecific;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.providerspecific.ProviderTransferMetadata</code>
 */
class ProviderTransferMetadata extends \Google\Protobuf\Internal\Message
{
    protected $metadata;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Providerspecific\Polishapi\PolishApiTransferMetadata $polish_api_transfer_metadata
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Providerspecific::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.PolishApiTransferMetadata polish_api_transfer_metadata = 1;</code>
     * @return \Io\Token\Proto\Common\Providerspecific\Polishapi\PolishApiTransferMetadata
     */
    public function getPolishApiTransferMetadata()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.PolishApiTransferMetadata polish_api_transfer_metadata = 1;</code>
     * @param \Io\Token\Proto\Common\Providerspecific\Polishapi\PolishApiTransferMetadata $var
     * @return $this
     */
    public function setPolishApiTransferMetadata($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Providerspecific\Polishapi\PolishApiTransferMetadata::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMetadata()
    {
        return $this->whichOneof("metadata");
    }

}

