<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: providerspecific.proto

namespace Io\Token\Proto\Common\Providerspecific;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.providerspecific.ProviderTransactionDetails</code>
 */
class ProviderTransactionDetails extends \Google\Protobuf\Internal\Message
{
    protected $details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Providerspecific\Polishapi\PolishApiTransactionDetails $polish_api_transaction_details
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Providerspecific::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.PolishApiTransactionDetails polish_api_transaction_details = 1;</code>
     * @return \Io\Token\Proto\Common\Providerspecific\Polishapi\PolishApiTransactionDetails
     */
    public function getPolishApiTransactionDetails()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.providerspecific.polishapi.PolishApiTransactionDetails polish_api_transaction_details = 1;</code>
     * @param \Io\Token\Proto\Common\Providerspecific\Polishapi\PolishApiTransactionDetails $var
     * @return $this
     */
    public function setPolishApiTransactionDetails($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Providerspecific\Polishapi\PolishApiTransactionDetails::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getDetails()
    {
        return $this->whichOneof("details");
    }

}

