<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transferinstructions.proto

namespace Io\Token\Proto\Common\Transferinstructions;

/**
 * A bank might require a context code for some transfers.
 *
 * Protobuf type <code>io.token.proto.common.transferinstructions.PaymentContext</code>
 */
class PaymentContext
{
    /**
     * Generated from protobuf enum <code>INVALID_CONTEXT = 0;</code>
     */
    const INVALID_CONTEXT = 0;
    /**
     * Generated from protobuf enum <code>OTHER_CONTEXT = 1;</code>
     */
    const OTHER_CONTEXT = 1;
    /**
     * Generated from protobuf enum <code>BILL_PAYMENT = 2;</code>
     */
    const BILL_PAYMENT = 2;
    /**
     * Generated from protobuf enum <code>ECOMMERCE_GOODS = 3;</code>
     */
    const ECOMMERCE_GOODS = 3;
    /**
     * Generated from protobuf enum <code>ECOMMERCE_SERVICES = 4;</code>
     */
    const ECOMMERCE_SERVICES = 4;
    /**
     * Generated from protobuf enum <code>PERSON_TO_PERSON = 5;</code>
     */
    const PERSON_TO_PERSON = 5;
}

