<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transferinstructions.proto

namespace Io\Token\Proto\Common\Transferinstructions;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Transferinstructions\TransferDestination\Chaps instead.
     * @deprecated
     */
    class TransferDestination_Chaps {}
}
class_exists(TransferDestination\Chaps::class);
@trigger_error('Io\Token\Proto\Common\Transferinstructions\TransferDestination_Chaps is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Transferinstructions\TransferDestination\Chaps instead', E_USER_DEPRECATED);

