<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transferinstructions.proto

namespace Io\Token\Proto\Common\Transferinstructions;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Transferinstructions\TransferDestination\Swift instead.
     * @deprecated
     */
    class TransferDestination_Swift {}
}
class_exists(TransferDestination\Swift::class);
@trigger_error('Io\Token\Proto\Common\Transferinstructions\TransferDestination_Swift is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Transferinstructions\TransferDestination\Swift instead', E_USER_DEPRECATED);

