<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transferinstructions.proto

namespace Io\Token\Proto\Common\Transferinstructions;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Transferinstructions\TransferInstructions\Metadata\ProviderSpecificMetadata\PolishApiMetadata instead.
     * @deprecated
     */
    class TransferInstructions_Metadata_ProviderSpecificMetadata_PolishApiMetadata {}
}
class_exists(TransferInstructions\Metadata\ProviderSpecificMetadata\PolishApiMetadata::class);
@trigger_error('Io\Token\Proto\Common\Transferinstructions\TransferInstructions_Metadata_ProviderSpecificMetadata_PolishApiMetadata is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Transferinstructions\TransferInstructions\Metadata\ProviderSpecificMetadata\PolishApiMetadata instead', E_USER_DEPRECATED);

