<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transferinstructions.proto

namespace Io\Token\Proto\Common\Transferinstructions;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Transferinstructions\TransferDestination\Bacs instead.
     * @deprecated
     */
    class TransferDestination_Bacs {}
}
class_exists(TransferDestination\Bacs::class);
@trigger_error('Io\Token\Proto\Common\Transferinstructions\TransferDestination_Bacs is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Transferinstructions\TransferDestination\Bacs instead', E_USER_DEPRECATED);

