<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eidas.proto

namespace Io\Token\Proto\Common\Eidas;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.eidas.RegisterWithEidasPayload</code>
 */
class RegisterWithEidasPayload extends \Google\Protobuf\Internal\Message
{
    /**
     * ID of the bank under whose realm a member should be created (e.g. "wood")
     *
     * Generated from protobuf field <code>string bank_id = 1;</code>
     */
    private $bank_id = '';
    /**
     * serialized eIDAS certificate
     *
     * Generated from protobuf field <code>string certificate = 2;</code>
     */
    private $certificate = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bank_id
     *           ID of the bank under whose realm a member should be created (e.g. "wood")
     *     @type string $certificate
     *           serialized eIDAS certificate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Eidas::initOnce();
        parent::__construct($data);
    }

    /**
     * ID of the bank under whose realm a member should be created (e.g. "wood")
     *
     * Generated from protobuf field <code>string bank_id = 1;</code>
     * @return string
     */
    public function getBankId()
    {
        return $this->bank_id;
    }

    /**
     * ID of the bank under whose realm a member should be created (e.g. "wood")
     *
     * Generated from protobuf field <code>string bank_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBankId($var)
    {
        GPBUtil::checkString($var, True);
        $this->bank_id = $var;

        return $this;
    }

    /**
     * serialized eIDAS certificate
     *
     * Generated from protobuf field <code>string certificate = 2;</code>
     * @return string
     */
    public function getCertificate()
    {
        return $this->certificate;
    }

    /**
     * serialized eIDAS certificate
     *
     * Generated from protobuf field <code>string certificate = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCertificate($var)
    {
        GPBUtil::checkString($var, True);
        $this->certificate = $var;

        return $this;
    }

}

