<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pricing.proto

namespace Io\Token\Proto\Common\Pricing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.pricing.PricingInstructions</code>
 */
class PricingInstructions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.io.token.proto.common.pricing.FeeResponsibility fees_paid_by = 1;</code>
     */
    private $fees_paid_by = 0;
    /**
     * Generated from protobuf field <code>.io.token.proto.common.pricing.FxResponsibility fx_performed_by = 2;</code>
     */
    private $fx_performed_by = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $fees_paid_by
     *     @type int $fx_performed_by
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pricing::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.pricing.FeeResponsibility fees_paid_by = 1;</code>
     * @return int
     */
    public function getFeesPaidBy()
    {
        return $this->fees_paid_by;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.pricing.FeeResponsibility fees_paid_by = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFeesPaidBy($var)
    {
        GPBUtil::checkEnum($var, \Io\Token\Proto\Common\Pricing\FeeResponsibility::class);
        $this->fees_paid_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.pricing.FxResponsibility fx_performed_by = 2;</code>
     * @return int
     */
    public function getFxPerformedBy()
    {
        return $this->fx_performed_by;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.pricing.FxResponsibility fx_performed_by = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFxPerformedBy($var)
    {
        GPBUtil::checkEnum($var, \Io\Token\Proto\Common\Pricing\FxResponsibility::class);
        $this->fx_performed_by = $var;

        return $this;
    }

}

