<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pricing.proto

namespace Io\Token\Proto\Common\Pricing;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Pricing\TransferQuote\FxRate instead.
     * @deprecated
     */
    class TransferQuote_FxRate {}
}
class_exists(TransferQuote\FxRate::class);
@trigger_error('Io\Token\Proto\Common\Pricing\TransferQuote_FxRate is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Pricing\TransferQuote\FxRate instead', E_USER_DEPRECATED);

