<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway\GetTokensRequest\TokenFilter;

/**
 * Protobuf type <code>io.token.proto.gateway.GetTokensRequest.TokenFilter.Role</code>
 */
class Role
{
    /**
     * Generated from protobuf enum <code>ANY = 0;</code>
     */
    const ANY = 0;
    /**
     * Generated from protobuf enum <code>FROM = 1;</code>
     */
    const FROM = 1;
    /**
     * Generated from protobuf enum <code>TO = 2;</code>
     */
    const TO = 2;
    /**
     * Generated from protobuf enum <code>ISSUER = 3;</code>
     */
    const ISSUER = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Role::class, \Io\Token\Proto\Gateway\GetTokensRequest_TokenFilter_Role::class);

