<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: providerspecific.proto

namespace Io\Token\Proto\Common\Providerspecific\Cma9AccountDetails;

/**
 * Protobuf type <code>io.token.proto.common.providerspecific.Cma9AccountDetails.PartyType</code>
 */
class PartyType
{
    /**
     * Generated from protobuf enum <code>INVALID_PARTY_TYPE = 0;</code>
     */
    const INVALID_PARTY_TYPE = 0;
    /**
     * Generated from protobuf enum <code>DELEGATE = 1;</code>
     */
    const DELEGATE = 1;
    /**
     * Generated from protobuf enum <code>JOINT = 2;</code>
     */
    const JOINT = 2;
    /**
     * Generated from protobuf enum <code>SOLE = 3;</code>
     */
    const SOLE = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PartyType::class, \Io\Token\Proto\Common\Providerspecific\Cma9AccountDetails_PartyType::class);

