<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsp/bankconfig.proto

namespace Io\Token\Proto\Common\Tsp\Bankconfig;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Tsp\Bankconfig\BankConfig\CzechPsd2Standard instead.
     * @deprecated
     */
    class BankConfig_CzechPsd2Standard {}
}
class_exists(BankConfig\CzechPsd2Standard::class);
@trigger_error('Io\Token\Proto\Common\Tsp\Bankconfig\BankConfig_CzechPsd2Standard is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Tsp\Bankconfig\BankConfig\CzechPsd2Standard instead', E_USER_DEPRECATED);

