<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsp/bankconfig.proto

namespace Io\Token\Proto\Common\Tsp\Bankconfig;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Tsp\Bankconfig\BankConfig\PolishApiStandard instead.
     * @deprecated
     */
    class BankConfig_PolishApiStandard {}
}
class_exists(BankConfig\PolishApiStandard::class);
@trigger_error('Io\Token\Proto\Common\Tsp\Bankconfig\BankConfig_PolishApiStandard is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Tsp\Bankconfig\BankConfig\PolishApiStandard instead', E_USER_DEPRECATED);

