<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: provider/cma9.proto

namespace Io\Token\Proto\Common\Providerspecific\Cma9;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Providerspecific\Cma9\Cma9AccountDetails\Cma9Address instead.
     * @deprecated
     */
    class Cma9AccountDetails_Cma9Address {}
}
class_exists(Cma9AccountDetails\Cma9Address::class);
@trigger_error('Io\Token\Proto\Common\Providerspecific\Cma9\Cma9AccountDetails_Cma9Address is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Providerspecific\Cma9\Cma9AccountDetails\Cma9Address instead', E_USER_DEPRECATED);

