<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.GetActiveAccessTokenRequest</code>
 */
class GetActiveAccessTokenRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Member ID of the recipient
     *
     * Generated from protobuf field <code>string to_member_id = 1;</code>
     */
    private $to_member_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $to_member_id
     *           Member ID of the recipient
     * }
     */
    public function __construct($data = NULL) {
        \Io\Token\GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * Member ID of the recipient
     *
     * Generated from protobuf field <code>string to_member_id = 1;</code>
     * @return string
     */
    public function getToMemberId()
    {
        return $this->to_member_id;
    }

    /**
     * Member ID of the recipient
     *
     * Generated from protobuf field <code>string to_member_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToMemberId($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_member_id = $var;

        return $this;
    }

}

