<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.GetBulkTransferResponse</code>
 */
class GetBulkTransferResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.io.token.proto.common.transfer.BulkTransfer bulk_transfer = 1;</code>
     */
    private $bulk_transfer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Transfer\BulkTransfer $bulk_transfer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.transfer.BulkTransfer bulk_transfer = 1;</code>
     * @return \Io\Token\Proto\Common\Transfer\BulkTransfer
     */
    public function getBulkTransfer()
    {
        return $this->bulk_transfer;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.transfer.BulkTransfer bulk_transfer = 1;</code>
     * @param \Io\Token\Proto\Common\Transfer\BulkTransfer $var
     * @return $this
     */
    public function setBulkTransfer($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Transfer\BulkTransfer::class);
        $this->bulk_transfer = $var;

        return $this;
    }

}

