<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.GetBankConfigResponse</code>
 */
class GetBankConfigResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.io.token.proto.common.tsp.bankconfig.BankConfig bank_config = 1;</code>
     */
    private $bank_config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Tsp\Bankconfig\BankConfig $bank_config
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.tsp.bankconfig.BankConfig bank_config = 1;</code>
     * @return \Io\Token\Proto\Common\Tsp\Bankconfig\BankConfig
     */
    public function getBankConfig()
    {
        return $this->bank_config;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.tsp.bankconfig.BankConfig bank_config = 1;</code>
     * @param \Io\Token\Proto\Common\Tsp\Bankconfig\BankConfig $var
     * @return $this
     */
    public function setBankConfig($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Tsp\Bankconfig\BankConfig::class);
        $this->bank_config = $var;

        return $this;
    }

}

