<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Gateway\GetBanksStatusResponse\BankStatus instead.
     * @deprecated
     */
    class GetBanksStatusResponse_BankStatus {}
}
class_exists(GetBanksStatusResponse\BankStatus::class);
@trigger_error('Io\Token\Proto\Gateway\GetBanksStatusResponse_BankStatus is deprecated and will be removed in the next major release. Use Io\Token\Proto\Gateway\GetBanksStatusResponse\BankStatus instead', E_USER_DEPRECATED);

