<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.GetBanksRequest</code>
 */
class GetBanksRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * (Optional) Filter by criteria in bank filter. Results must match all filter criteria.
     *
     * Generated from protobuf field <code>.io.token.proto.common.bank.BankFilter filter = 9;</code>
     */
    private $filter = null;
    /**
     * Paging
     *
     * Generated from protobuf field <code>int32 page = 4;</code>
     */
    private $page = 0;
    /**
     * Maximum number of records per page. Can be at most 200. Defaults to 200 if not specified.
     *
     * Generated from protobuf field <code>int32 per_page = 5;</code>
     */
    private $per_page = 0;
    /**
     * The key to sort the results. Could be one of: name, provider and country. Defaults to name if not specified.
     *
     * Generated from protobuf field <code>string sort = 6;</code>
     */
    private $sort = '';
    /**
     * DEPRECATED
     *
     * Generated from protobuf field <code>string country = 3 [deprecated = true];</code>
     */
    private $country = '';
    /**
     * DEPRECATED. If specified, return banks whose 'id' matches any one of the given ids (case-insensitive). Can be at most 1000.
     *
     * Generated from protobuf field <code>repeated string ids = 1 [deprecated = true];</code>
     */
    private $ids;
    /**
     * DEPRECATED. If specified, return banks whose 'name' or 'identifier' contains the given search string (case-insensitive)
     *
     * Generated from protobuf field <code>string search = 2 [deprecated = true];</code>
     */
    private $search = '';
    /**
     * DEPRECATED. (Optional) If specified, return banks whose 'provider' matches the provider (case-insensitive)
     *
     * Generated from protobuf field <code>string provider = 7 [deprecated = true];</code>
     */
    private $provider = '';
    /**
     * DEPRECATED. (Optional) If specified, return banks which are integrated with the TPP
     *
     * Generated from protobuf field <code>string tpp_id = 8 [deprecated = true];</code>
     */
    private $tpp_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Bank\BankFilter $filter
     *           (Optional) Filter by criteria in bank filter. Results must match all filter criteria.
     *     @type int $page
     *           Paging
     *     @type int $per_page
     *           Maximum number of records per page. Can be at most 200. Defaults to 200 if not specified.
     *     @type string $sort
     *           The key to sort the results. Could be one of: name, provider and country. Defaults to name if not specified.
     *     @type string $country
     *           DEPRECATED
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $ids
     *           DEPRECATED. If specified, return banks whose 'id' matches any one of the given ids (case-insensitive). Can be at most 1000.
     *     @type string $search
     *           DEPRECATED. If specified, return banks whose 'name' or 'identifier' contains the given search string (case-insensitive)
     *     @type string $provider
     *           DEPRECATED. (Optional) If specified, return banks whose 'provider' matches the provider (case-insensitive)
     *     @type string $tpp_id
     *           DEPRECATED. (Optional) If specified, return banks which are integrated with the TPP
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * (Optional) Filter by criteria in bank filter. Results must match all filter criteria.
     *
     * Generated from protobuf field <code>.io.token.proto.common.bank.BankFilter filter = 9;</code>
     * @return \Io\Token\Proto\Common\Bank\BankFilter
     */
    public function getFilter()
    {
        return $this->filter;
    }

    /**
     * (Optional) Filter by criteria in bank filter. Results must match all filter criteria.
     *
     * Generated from protobuf field <code>.io.token.proto.common.bank.BankFilter filter = 9;</code>
     * @param \Io\Token\Proto\Common\Bank\BankFilter $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Bank\BankFilter::class);
        $this->filter = $var;

        return $this;
    }

    /**
     * Paging
     *
     * Generated from protobuf field <code>int32 page = 4;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Paging
     *
     * Generated from protobuf field <code>int32 page = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     * Maximum number of records per page. Can be at most 200. Defaults to 200 if not specified.
     *
     * Generated from protobuf field <code>int32 per_page = 5;</code>
     * @return int
     */
    public function getPerPage()
    {
        return $this->per_page;
    }

    /**
     * Maximum number of records per page. Can be at most 200. Defaults to 200 if not specified.
     *
     * Generated from protobuf field <code>int32 per_page = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setPerPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->per_page = $var;

        return $this;
    }

    /**
     * The key to sort the results. Could be one of: name, provider and country. Defaults to name if not specified.
     *
     * Generated from protobuf field <code>string sort = 6;</code>
     * @return string
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * The key to sort the results. Could be one of: name, provider and country. Defaults to name if not specified.
     *
     * Generated from protobuf field <code>string sort = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSort($var)
    {
        GPBUtil::checkString($var, True);
        $this->sort = $var;

        return $this;
    }

    /**
     * DEPRECATED
     *
     * Generated from protobuf field <code>string country = 3 [deprecated = true];</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * DEPRECATED
     *
     * Generated from protobuf field <code>string country = 3 [deprecated = true];</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

    /**
     * DEPRECATED. If specified, return banks whose 'id' matches any one of the given ids (case-insensitive). Can be at most 1000.
     *
     * Generated from protobuf field <code>repeated string ids = 1 [deprecated = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIds()
    {
        return $this->ids;
    }

    /**
     * DEPRECATED. If specified, return banks whose 'id' matches any one of the given ids (case-insensitive). Can be at most 1000.
     *
     * Generated from protobuf field <code>repeated string ids = 1 [deprecated = true];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ids = $arr;

        return $this;
    }

    /**
     * DEPRECATED. If specified, return banks whose 'name' or 'identifier' contains the given search string (case-insensitive)
     *
     * Generated from protobuf field <code>string search = 2 [deprecated = true];</code>
     * @return string
     */
    public function getSearch()
    {
        return $this->search;
    }

    /**
     * DEPRECATED. If specified, return banks whose 'name' or 'identifier' contains the given search string (case-insensitive)
     *
     * Generated from protobuf field <code>string search = 2 [deprecated = true];</code>
     * @param string $var
     * @return $this
     */
    public function setSearch($var)
    {
        GPBUtil::checkString($var, True);
        $this->search = $var;

        return $this;
    }

    /**
     * DEPRECATED. (Optional) If specified, return banks whose 'provider' matches the provider (case-insensitive)
     *
     * Generated from protobuf field <code>string provider = 7 [deprecated = true];</code>
     * @return string
     */
    public function getProvider()
    {
        return $this->provider;
    }

    /**
     * DEPRECATED. (Optional) If specified, return banks whose 'provider' matches the provider (case-insensitive)
     *
     * Generated from protobuf field <code>string provider = 7 [deprecated = true];</code>
     * @param string $var
     * @return $this
     */
    public function setProvider($var)
    {
        GPBUtil::checkString($var, True);
        $this->provider = $var;

        return $this;
    }

    /**
     * DEPRECATED. (Optional) If specified, return banks which are integrated with the TPP
     *
     * Generated from protobuf field <code>string tpp_id = 8 [deprecated = true];</code>
     * @return string
     */
    public function getTppId()
    {
        return $this->tpp_id;
    }

    /**
     * DEPRECATED. (Optional) If specified, return banks which are integrated with the TPP
     *
     * Generated from protobuf field <code>string tpp_id = 8 [deprecated = true];</code>
     * @param string $var
     * @return $this
     */
    public function setTppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->tpp_id = $var;

        return $this;
    }

}

