<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Gateway\GetBankDowntimeReportResponse\BankDowntimeSummary instead.
     * @deprecated
     */
    class GetBankDowntimeReportResponse_BankDowntimeSummary {}
}
class_exists(GetBankDowntimeReportResponse\BankDowntimeSummary::class);
@trigger_error('Io\Token\Proto\Gateway\GetBankDowntimeReportResponse_BankDowntimeSummary is deprecated and will be removed in the next major release. Use Io\Token\Proto\Gateway\GetBankDowntimeReportResponse\BankDowntimeSummary instead', E_USER_DEPRECATED);

