<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.GetConsentsResponse</code>
 */
class GetConsentsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .io.token.proto.common.consent.Consent consents = 1;</code>
     */
    private $consents;
    /**
     * Generated from protobuf field <code>string offset = 2;</code>
     */
    private $offset = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Consent\Consent[]|\Google\Protobuf\Internal\RepeatedField $consents
     *     @type string $offset
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .io.token.proto.common.consent.Consent consents = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConsents()
    {
        return $this->consents;
    }

    /**
     * Generated from protobuf field <code>repeated .io.token.proto.common.consent.Consent consents = 1;</code>
     * @param \Io\Token\Proto\Common\Consent\Consent[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConsents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Token\Proto\Common\Consent\Consent::class);
        $this->consents = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string offset = 2;</code>
     * @return string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Generated from protobuf field <code>string offset = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkString($var, True);
        $this->offset = $var;

        return $this;
    }

}

