<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.GetPairedDevicesResponse</code>
 */
class GetPairedDevicesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * linked device info
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.member.Device devices = 1;</code>
     */
    private $devices;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Member\Device[]|\Google\Protobuf\Internal\RepeatedField $devices
     *           linked device info
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * linked device info
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.member.Device devices = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDevices()
    {
        return $this->devices;
    }

    /**
     * linked device info
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.member.Device devices = 1;</code>
     * @param \Io\Token\Proto\Common\Member\Device[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDevices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Token\Proto\Common\Member\Device::class);
        $this->devices = $arr;

        return $this;
    }

}

