<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.GetTokensResponse</code>
 */
class GetTokensResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * list of Tokens
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.token.Token tokens = 1;</code>
     */
    private $tokens;
    /**
     * optional offset state for the client to roundtrip.
     *
     * Generated from protobuf field <code>string offset = 2;</code>
     */
    private $offset = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Token\Token[]|\Google\Protobuf\Internal\RepeatedField $tokens
     *           list of Tokens
     *     @type string $offset
     *           optional offset state for the client to roundtrip.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * list of Tokens
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.token.Token tokens = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * list of Tokens
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.token.Token tokens = 1;</code>
     * @param \Io\Token\Proto\Common\Token\Token[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTokens($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Token\Proto\Common\Token\Token::class);
        $this->tokens = $arr;

        return $this;
    }

    /**
     * optional offset state for the client to roundtrip.
     *
     * Generated from protobuf field <code>string offset = 2;</code>
     * @return string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * optional offset state for the client to roundtrip.
     *
     * Generated from protobuf field <code>string offset = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkString($var, True);
        $this->offset = $var;

        return $this;
    }

}

