<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.GetTransactionsRequest</code>
 */
class GetTransactionsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string account_id = 1;</code>
     */
    private $account_id = '';
    /**
     * Optional paging settings.
     *
     * Generated from protobuf field <code>.io.token.proto.gateway.Page page = 2;</code>
     */
    private $page = null;
    /**
     * for backwards compatibility with older JS clients TODO(RD-2738) remove
     *
     * Generated from protobuf field <code>string offset = 3 [deprecated = true];</code>
     */
    private $offset = '';
    /**
     * Generated from protobuf field <code>int32 limit = 4 [deprecated = true];</code>
     */
    private $limit = 0;
    /**
     * Optional lower bound for a transaction's booking date as returned by the bank, in the format 'YYYY-MM-DD' (e.g. '2016-01-01').
     * If specified, then only transactions whose bank booking date is equal to or later than the given date will be regarded.
     *
     * Generated from protobuf field <code>string start_date = 5;</code>
     */
    private $start_date = '';
    /**
     * Optional upper bound for a transaction's booking date as returned by the bank (= original booking date), in the format 'YYYY-MM-DD' (e.g. '2016-01-01').
     * If specified, then only transactions whose bank booking date is equal to or earlier than the given date will be regarded.
     *
     * Generated from protobuf field <code>string end_date = 6;</code>
     */
    private $end_date = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $account_id
     *     @type \Io\Token\Proto\Gateway\Page $page
     *           Optional paging settings.
     *     @type string $offset
     *           for backwards compatibility with older JS clients TODO(RD-2738) remove
     *     @type int $limit
     *     @type string $start_date
     *           Optional lower bound for a transaction's booking date as returned by the bank, in the format 'YYYY-MM-DD' (e.g. '2016-01-01').
     *           If specified, then only transactions whose bank booking date is equal to or later than the given date will be regarded.
     *     @type string $end_date
     *           Optional upper bound for a transaction's booking date as returned by the bank (= original booking date), in the format 'YYYY-MM-DD' (e.g. '2016-01-01').
     *           If specified, then only transactions whose bank booking date is equal to or earlier than the given date will be regarded.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string account_id = 1;</code>
     * @return string
     */
    public function getAccountId()
    {
        return $this->account_id;
    }

    /**
     * Generated from protobuf field <code>string account_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountId($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_id = $var;

        return $this;
    }

    /**
     * Optional paging settings.
     *
     * Generated from protobuf field <code>.io.token.proto.gateway.Page page = 2;</code>
     * @return \Io\Token\Proto\Gateway\Page
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * Optional paging settings.
     *
     * Generated from protobuf field <code>.io.token.proto.gateway.Page page = 2;</code>
     * @param \Io\Token\Proto\Gateway\Page $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Gateway\Page::class);
        $this->page = $var;

        return $this;
    }

    /**
     * for backwards compatibility with older JS clients TODO(RD-2738) remove
     *
     * Generated from protobuf field <code>string offset = 3 [deprecated = true];</code>
     * @return string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * for backwards compatibility with older JS clients TODO(RD-2738) remove
     *
     * Generated from protobuf field <code>string offset = 3 [deprecated = true];</code>
     * @param string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkString($var, True);
        $this->offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 4 [deprecated = true];</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Generated from protobuf field <code>int32 limit = 4 [deprecated = true];</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Optional lower bound for a transaction's booking date as returned by the bank, in the format 'YYYY-MM-DD' (e.g. '2016-01-01').
     * If specified, then only transactions whose bank booking date is equal to or later than the given date will be regarded.
     *
     * Generated from protobuf field <code>string start_date = 5;</code>
     * @return string
     */
    public function getStartDate()
    {
        return $this->start_date;
    }

    /**
     * Optional lower bound for a transaction's booking date as returned by the bank, in the format 'YYYY-MM-DD' (e.g. '2016-01-01').
     * If specified, then only transactions whose bank booking date is equal to or later than the given date will be regarded.
     *
     * Generated from protobuf field <code>string start_date = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStartDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->start_date = $var;

        return $this;
    }

    /**
     * Optional upper bound for a transaction's booking date as returned by the bank (= original booking date), in the format 'YYYY-MM-DD' (e.g. '2016-01-01').
     * If specified, then only transactions whose bank booking date is equal to or earlier than the given date will be regarded.
     *
     * Generated from protobuf field <code>string end_date = 6;</code>
     * @return string
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    /**
     * Optional upper bound for a transaction's booking date as returned by the bank (= original booking date), in the format 'YYYY-MM-DD' (e.g. '2016-01-01').
     * If specified, then only transactions whose bank booking date is equal to or earlier than the given date will be regarded.
     *
     * Generated from protobuf field <code>string end_date = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setEndDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->end_date = $var;

        return $this;
    }

}

