<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.NotifyRequest</code>
 */
class NotifyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * alias of member to notify
     *
     * Generated from protobuf field <code>.io.token.proto.common.alias.Alias alias = 1;</code>
     */
    private $alias = null;
    /**
     * notification details
     *
     * Generated from protobuf field <code>.io.token.proto.common.notification.NotifyBody body = 2;</code>
     */
    private $body = null;
    /**
     * Deprecated
     *
     * Generated from protobuf field <code>string realm = 3;</code>
     */
    private $realm = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Alias\Alias $alias
     *           alias of member to notify
     *     @type \Io\Token\Proto\Common\Notification\NotifyBody $body
     *           notification details
     *     @type string $realm
     *           Deprecated
     * }
     */
    public function __construct($data = NULL) {
        \Io\Token\GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * alias of member to notify
     *
     * Generated from protobuf field <code>.io.token.proto.common.alias.Alias alias = 1;</code>
     * @return \Io\Token\Proto\Common\Alias\Alias
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * alias of member to notify
     *
     * Generated from protobuf field <code>.io.token.proto.common.alias.Alias alias = 1;</code>
     * @param \Io\Token\Proto\Common\Alias\Alias $var
     * @return $this
     */
    public function setAlias($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Alias\Alias::class);
        $this->alias = $var;

        return $this;
    }

    /**
     * notification details
     *
     * Generated from protobuf field <code>.io.token.proto.common.notification.NotifyBody body = 2;</code>
     * @return \Io\Token\Proto\Common\Notification\NotifyBody
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * notification details
     *
     * Generated from protobuf field <code>.io.token.proto.common.notification.NotifyBody body = 2;</code>
     * @param \Io\Token\Proto\Common\Notification\NotifyBody $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Notification\NotifyBody::class);
        $this->body = $var;

        return $this;
    }

    /**
     * Deprecated
     *
     * Generated from protobuf field <code>string realm = 3;</code>
     * @return string
     */
    public function getRealm()
    {
        return $this->realm;
    }

    /**
     * Deprecated
     *
     * Generated from protobuf field <code>string realm = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRealm($var)
    {
        GPBUtil::checkString($var, True);
        $this->realm = $var;

        return $this;
    }

}

