<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#47;/////////////////////////////////////////////////////////////////////////////////////////////////
 * Paging details.
 *
 * Generated from protobuf message <code>io.token.proto.gateway.Page</code>
 */
class Page extends \Google\Protobuf\Internal\Message
{
    /**
     * Opaque base-64 encoded offset for the client to roundtrip.
     *
     * Generated from protobuf field <code>string offset = 1;</code>
     */
    private $offset = '';
    /**
     * Max number of records to return.
     *
     * Generated from protobuf field <code>int32 limit = 2;</code>
     */
    private $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $offset
     *           Opaque base-64 encoded offset for the client to roundtrip.
     *     @type int $limit
     *           Max number of records to return.
     * }
     */
    public function __construct($data = NULL) {
        \Io\Token\GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * Opaque base-64 encoded offset for the client to roundtrip.
     *
     * Generated from protobuf field <code>string offset = 1;</code>
     * @return string
     */
    public function getOffset()
    {
        return $this->offset;
    }

    /**
     * Opaque base-64 encoded offset for the client to roundtrip.
     *
     * Generated from protobuf field <code>string offset = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOffset($var)
    {
        GPBUtil::checkString($var, True);
        $this->offset = $var;

        return $this;
    }

    /**
     * Max number of records to return.
     *
     * Generated from protobuf field <code>int32 limit = 2;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * Max number of records to return.
     *
     * Generated from protobuf field <code>int32 limit = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

}

