<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.RecoverEidasResponse</code>
 */
class RecoverEidasResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.io.token.proto.common.member.MemberRecoveryOperation recovery_entry = 1;</code>
     */
    private $recovery_entry = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Member\MemberRecoveryOperation $recovery_entry
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.member.MemberRecoveryOperation recovery_entry = 1;</code>
     * @return \Io\Token\Proto\Common\Member\MemberRecoveryOperation
     */
    public function getRecoveryEntry()
    {
        return $this->recovery_entry;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.member.MemberRecoveryOperation recovery_entry = 1;</code>
     * @param \Io\Token\Proto\Common\Member\MemberRecoveryOperation $var
     * @return $this
     */
    public function setRecoveryEntry($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Member\MemberRecoveryOperation::class);
        $this->recovery_entry = $var;

        return $this;
    }

}

