<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.RequestTransferRequest</code>
 */
class RequestTransferRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * transfer token payload with some values filled in
     *
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenPayload token_payload = 2;</code>
     */
    private $token_payload = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Io\Token\Proto\Common\Token\TokenPayload $token_payload
     *           transfer token payload with some values filled in
     * }
     */
    public function __construct($data = NULL) {
        \Io\Token\GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * transfer token payload with some values filled in
     *
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenPayload token_payload = 2;</code>
     * @return \Io\Token\Proto\Common\Token\TokenPayload
     */
    public function getTokenPayload()
    {
        return $this->token_payload;
    }

    /**
     * transfer token payload with some values filled in
     *
     * Generated from protobuf field <code>.io.token.proto.common.token.TokenPayload token_payload = 2;</code>
     * @param \Io\Token\Proto\Common\Token\TokenPayload $var
     * @return $this
     */
    public function setTokenPayload($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Token\TokenPayload::class);
        $this->token_payload = $var;

        return $this;
    }

}

