<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

namespace Io\Token\Proto\Gateway;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.gateway.SetAppCallbackUrlRequest</code>
 */
class SetAppCallbackUrlRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * the custom app call back url
     *
     * Generated from protobuf field <code>string app_callback_url = 1;</code>
     */
    private $app_callback_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $app_callback_url
     *           the custom app call back url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Gateway\Gateway::initOnce();
        parent::__construct($data);
    }

    /**
     * the custom app call back url
     *
     * Generated from protobuf field <code>string app_callback_url = 1;</code>
     * @return string
     */
    public function getAppCallbackUrl()
    {
        return $this->app_callback_url;
    }

    /**
     * the custom app call back url
     *
     * Generated from protobuf field <code>string app_callback_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppCallbackUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_callback_url = $var;

        return $this;
    }

}

