<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bankinfo.proto

namespace Io\Token\Proto\Common\Bank;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Bank\BankFilter\BankFeatures instead.
     * @deprecated
     */
    class BankFilter_BankFeatures {}
}
class_exists(BankFilter\BankFeatures::class);
@trigger_error('Io\Token\Proto\Common\Bank\BankFilter_BankFeatures is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Bank\BankFilter\BankFeatures instead', E_USER_DEPRECATED);

