<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tsp/bankconfig.proto

namespace Io\Token\Proto\Common\Tsp\Bankconfig\BankConfig;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.tsp.bankconfig.BankConfig.StarlingApiStandard</code>
 */
class StarlingApiStandard extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ais_client_id = 1;</code>
     */
    private $ais_client_id = '';
    /**
     * Generated from protobuf field <code>string ais_client_secret = 2;</code>
     */
    private $ais_client_secret = '';
    /**
     * Generated from protobuf field <code>string pis_client_id = 3;</code>
     */
    private $pis_client_id = '';
    /**
     * Generated from protobuf field <code>string pis_client_secret = 4;</code>
     */
    private $pis_client_secret = '';
    /**
     * Generated from protobuf field <code>string jwt_signing_key_id = 5;</code>
     */
    private $jwt_signing_key_id = '';
    /**
     * Generated from protobuf field <code>string signing_key_id = 6;</code>
     */
    private $signing_key_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ais_client_id
     *     @type string $ais_client_secret
     *     @type string $pis_client_id
     *     @type string $pis_client_secret
     *     @type string $jwt_signing_key_id
     *     @type string $signing_key_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tsp\Bankconfig::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ais_client_id = 1;</code>
     * @return string
     */
    public function getAisClientId()
    {
        return $this->ais_client_id;
    }

    /**
     * Generated from protobuf field <code>string ais_client_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAisClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ais_client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ais_client_secret = 2;</code>
     * @return string
     */
    public function getAisClientSecret()
    {
        return $this->ais_client_secret;
    }

    /**
     * Generated from protobuf field <code>string ais_client_secret = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAisClientSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->ais_client_secret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pis_client_id = 3;</code>
     * @return string
     */
    public function getPisClientId()
    {
        return $this->pis_client_id;
    }

    /**
     * Generated from protobuf field <code>string pis_client_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPisClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->pis_client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pis_client_secret = 4;</code>
     * @return string
     */
    public function getPisClientSecret()
    {
        return $this->pis_client_secret;
    }

    /**
     * Generated from protobuf field <code>string pis_client_secret = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPisClientSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->pis_client_secret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string jwt_signing_key_id = 5;</code>
     * @return string
     */
    public function getJwtSigningKeyId()
    {
        return $this->jwt_signing_key_id;
    }

    /**
     * Generated from protobuf field <code>string jwt_signing_key_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setJwtSigningKeyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->jwt_signing_key_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string signing_key_id = 6;</code>
     * @return string
     */
    public function getSigningKeyId()
    {
        return $this->signing_key_id;
    }

    /**
     * Generated from protobuf field <code>string signing_key_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSigningKeyId($var)
    {
        GPBUtil::checkString($var, True);
        $this->signing_key_id = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StarlingApiStandard::class, \Io\Token\Proto\Common\Tsp\Bankconfig\BankConfig_StarlingApiStandard::class);

