<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto

namespace Io\Token\Proto\Common\Token;

if (false) {
    /**
     * This class is deprecated. Use Io\Token\Proto\Common\Token\AccessBody\Resource\AllAccountBalances instead.
     * @deprecated
     */
    class AccessBody_Resource_AllAccountBalances {}
}
class_exists(AccessBody\Resource\AllAccountBalances::class);
@trigger_error('Io\Token\Proto\Common\Token\AccessBody_Resource_AllAccountBalances is deprecated and will be removed in the next major release. Use Io\Token\Proto\Common\Token\AccessBody\Resource\AllAccountBalances instead', E_USER_DEPRECATED);

