<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Io\Token\Proto\Common\Account\BankAccount;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>io.token.proto.common.account.BankAccount.Domestic</code>
 */
class Domestic extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string bank_code = 1;</code>
     */
    private $bank_code = '';
    /**
     * Generated from protobuf field <code>string account_number = 2;</code>
     */
    private $account_number = '';
    /**
     * 2-letter ISO 3166-1 alpha-2 country code
     *
     * Generated from protobuf field <code>string country = 3;</code>
     */
    private $country = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bank_code
     *     @type string $account_number
     *     @type string $country
     *           2-letter ISO 3166-1 alpha-2 country code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string bank_code = 1;</code>
     * @return string
     */
    public function getBankCode()
    {
        return $this->bank_code;
    }

    /**
     * Generated from protobuf field <code>string bank_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBankCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->bank_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string account_number = 2;</code>
     * @return string
     */
    public function getAccountNumber()
    {
        return $this->account_number;
    }

    /**
     * Generated from protobuf field <code>string account_number = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAccountNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->account_number = $var;

        return $this;
    }

    /**
     * 2-letter ISO 3166-1 alpha-2 country code
     *
     * Generated from protobuf field <code>string country = 3;</code>
     * @return string
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * 2-letter ISO 3166-1 alpha-2 country code
     *
     * Generated from protobuf field <code>string country = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Domestic::class, \Io\Token\Proto\Common\Account\BankAccount_Domestic::class);

