<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Io\Token\Proto\Common\Account\BankAccount;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SWIFT transfer
 *
 * Generated from protobuf message <code>io.token.proto.common.account.BankAccount.Swift</code>
 */
class Swift extends \Google\Protobuf\Internal\Message
{
    /**
     * BIC code AAAABBCCDD
     *
     * Generated from protobuf field <code>string bic = 1;</code>
     */
    private $bic = '';
    /**
     * Generated from protobuf field <code>string account = 2;</code>
     */
    private $account = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bic
     *           BIC code AAAABBCCDD
     *     @type string $account
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * BIC code AAAABBCCDD
     *
     * Generated from protobuf field <code>string bic = 1;</code>
     * @return string
     */
    public function getBic()
    {
        return $this->bic;
    }

    /**
     * BIC code AAAABBCCDD
     *
     * Generated from protobuf field <code>string bic = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBic($var)
    {
        GPBUtil::checkString($var, True);
        $this->bic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string account = 2;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>string account = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->account = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Swift::class, \Io\Token\Proto\Common\Account\BankAccount_Swift::class);

