<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto

namespace Io\Token\Proto\Common\Notification;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A notification that a key wants to be added to a member. Clients should timeout the notification
 * and screen, once the expires_ms has passed
 *
 * Generated from protobuf message <code>io.token.proto.common.notification.AddKey</code>
 */
class AddKey extends \Google\Protobuf\Internal\Message
{
    /**
     * **DEPRECATED** Human-readable name, e.g., "Chrome Browser" or "My App"
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * **DEPRECATED** Key
     *
     * Generated from protobuf field <code>.io.token.proto.common.security.Key key = 2;</code>
     */
    private $key = null;
    /**
     * Expiration time
     *
     * Generated from protobuf field <code>int64 expires_ms = 3;</code>
     */
    private $expires_ms = 0;
    /**
     * List of new keys to add
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.security.Key keys = 4;</code>
     */
    private $keys;
    /**
     * Generated from protobuf field <code>.io.token.proto.common.notification.DeviceMetadata device_metadata = 5;</code>
     */
    private $device_metadata = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           **DEPRECATED** Human-readable name, e.g., "Chrome Browser" or "My App"
     *     @type \Io\Token\Proto\Common\Security\Key $key
     *           **DEPRECATED** Key
     *     @type int|string $expires_ms
     *           Expiration time
     *     @type \Io\Token\Proto\Common\Security\Key[]|\Google\Protobuf\Internal\RepeatedField $keys
     *           List of new keys to add
     *     @type \Io\Token\Proto\Common\Notification\DeviceMetadata $device_metadata
     * }
     */
    public function __construct($data = NULL) {
        \Io\Token\GPBMetadata\Notification::initOnce();
        parent::__construct($data);
    }

    /**
     * **DEPRECATED** Human-readable name, e.g., "Chrome Browser" or "My App"
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * **DEPRECATED** Human-readable name, e.g., "Chrome Browser" or "My App"
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * **DEPRECATED** Key
     *
     * Generated from protobuf field <code>.io.token.proto.common.security.Key key = 2;</code>
     * @return \Io\Token\Proto\Common\Security\Key
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * **DEPRECATED** Key
     *
     * Generated from protobuf field <code>.io.token.proto.common.security.Key key = 2;</code>
     * @param \Io\Token\Proto\Common\Security\Key $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Security\Key::class);
        $this->key = $var;

        return $this;
    }

    /**
     * Expiration time
     *
     * Generated from protobuf field <code>int64 expires_ms = 3;</code>
     * @return int|string
     */
    public function getExpiresMs()
    {
        return $this->expires_ms;
    }

    /**
     * Expiration time
     *
     * Generated from protobuf field <code>int64 expires_ms = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiresMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->expires_ms = $var;

        return $this;
    }

    /**
     * List of new keys to add
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.security.Key keys = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * List of new keys to add
     *
     * Generated from protobuf field <code>repeated .io.token.proto.common.security.Key keys = 4;</code>
     * @param \Io\Token\Proto\Common\Security\Key[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Io\Token\Proto\Common\Security\Key::class);
        $this->keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.notification.DeviceMetadata device_metadata = 5;</code>
     * @return \Io\Token\Proto\Common\Notification\DeviceMetadata
     */
    public function getDeviceMetadata()
    {
        return $this->device_metadata;
    }

    /**
     * Generated from protobuf field <code>.io.token.proto.common.notification.DeviceMetadata device_metadata = 5;</code>
     * @param \Io\Token\Proto\Common\Notification\DeviceMetadata $var
     * @return $this
     */
    public function setDeviceMetadata($var)
    {
        GPBUtil::checkMessage($var, \Io\Token\Proto\Common\Notification\DeviceMetadata::class);
        $this->device_metadata = $var;

        return $this;
    }

}

