<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banklink.proto

namespace Io\Token\Proto\Banklink;

/**
 * Protobuf type <code>io.token.proto.banklink.AccountLinkingStatus</code>
 */
class AccountLinkingStatus
{
    /**
     * Generated from protobuf enum <code>INVALID = 0;</code>
     */
    const INVALID = 0;
    /**
     * Generated from protobuf enum <code>SUCCESS = 1;</code>
     */
    const SUCCESS = 1;
    /**
     * indicates that a bank authorization payload
     *
     * Generated from protobuf enum <code>FAILURE_BANK_AUTHORIZATION_REQUIRED = 2;</code>
     */
    const FAILURE_BANK_AUTHORIZATION_REQUIRED = 2;
}

